{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.coop-sa.read-keyboard": {
            "addr": "0x4308d3",
            "expected": "a110574a00",
            "code": "E8 [codecave:of(ExpHP.coop-sa.read-keyboard)]"
        },
        "ExpHP.coop-sa.always-update-options": {
            "addr": "0x4337c7",
            "expected": "0f8549010000",
            "code": "E9 [codecave:of(ExpHP.coop-sa.always-update-options)] // CC"
        },
        "ExpHP.coop-sa.read-attempted-motion": {
            "addr": "0x43381a",
            "expected": "d986b0080000d986ac080000",
            "code": "E8 [codecave:of(ExpHP.coop-sa.read-attempted-motion)] // 90909090909090"
        },
        "ExpHP.coop-sa.read-attempted-x": {
            "addr": "0x4337da",
            "expected": "d986a0080000",
            "code": "E8 [codecave:of(ExpHP.coop-sa.read-attempted-x)] // 90"
        },
        "ExpHP.coop-sa.read-attempted-y": {
            "addr": "0x4337fb",
            "expected": "d986a4080000",
            "code": "E8 [codecave:of(ExpHP.coop-sa.read-attempted-y)] // 90"
        },
        "ExpHP.coop-sa.reimu-c-angle-fld": {
            "addr": [
                "0x43383a",
                "0x433879"
            ],
            "expected": "d986148c0000",
            "code": "E8 [codecave:of(ExpHP.coop-sa.reimu-c-angle-fld)] // 90"
        },
        "ExpHP.coop-sa.reimu-c-angle-fstp": {
            "addr": [
                "0x433910"
            ],
            "expected": "d99e148c0000",
            "code": "E8 [codecave:of(ExpHP.coop-sa.reimu-c-angle-fstp)] // 90"
        },
        "ExpHP.coop-sa.reimu-c-angle-fadd": {
            "addr": [
                "0x4338f9",
                "0x4338d3",
                "0x433921"
            ],
            "expected": "d886148c0000",
            "code": "E8 [codecave:of(ExpHP.coop-sa.reimu-c-angle-fadd)] // 90"
        },
        "ExpHP.coop-sa.power-at-least-2": {
            "addr": "0x432cd9",
            "expected": "8b0de8564a00",
            "code": "E8 [codecave:of(ExpHP.coop-sa.power-at-least-2)] // 90"
        },
        "ExpHP.coop-sa.bomb-requires-power-3": {
            "addr": "0x4311d3",
            "expected": "f73d4c574a0085c0",
            "code": "E8 [codecave:of(ExpHP.coop-sa.bomb-requires-power-3)] // 909090"
        },
        "ExpHP.coop-sa.different-color-options(28, 40, 25, 4402667)": {
            "expected": "6a0b6a198d742428",
            "addr": [
                "0x432de3"
            ],
            "code": "E9 [codecave:of(ExpHP.coop-sa.different-color-options(28, 40, 25, 4402667))] // CCCCCC"
        },
        "ExpHP.coop-sa.different-color-options(104, 64, 22, 4403672)": {
            "expected": "6a0b6a168d742440",
            "addr": [
                "0x4331d0"
            ],
            "code": "E9 [codecave:of(ExpHP.coop-sa.different-color-options(104, 64, 22, 4403672))] // CCCCCC"
        }
    },
    "codecaves": {
        "of(ExpHP.coop-sa.read-keyboard)": "e8[codecave:ExpHP.coop-sa.update-keyboard]a110574a00c3",
        "of(ExpHP.coop-sa.always-update-options)": "e800000000c70424da374300c3",
        "of(ExpHP.coop-sa.read-attempted-motion)": "83ec0854ffb7d0000000e8[codecave:ExpHP.coop-sa.get-option-attempted-motion]d9442404d9042483c408c3",
        "of(ExpHP.coop-sa.read-attempted-x)": "83ec0854ffb7d0000000e8[codecave:ExpHP.coop-sa.get-option-attempted-motion]d9042483c408c3",
        "of(ExpHP.coop-sa.read-attempted-y)": "83ec0854ffb7d0000000e8[codecave:ExpHP.coop-sa.get-option-attempted-motion]d944240483c408c3",
        "of(ExpHP.coop-sa.reimu-c-angle-fld)": "ffb7d0000000e8[codecave:ExpHP.coop-sa.get-option-angle-ptr]d900c3",
        "of(ExpHP.coop-sa.reimu-c-angle-fstp)": "ffb7d0000000e8[codecave:ExpHP.coop-sa.get-option-angle-ptr]d918c3",
        "of(ExpHP.coop-sa.reimu-c-angle-fadd)": "ffb7d0000000e8[codecave:ExpHP.coop-sa.get-option-angle-ptr]d800c3",
        "of(ExpHP.coop-sa.power-at-least-2)": "8b0de8564a0083f9287d0ac705e8564a00280000008b0de8564a00c3",
        "of(ExpHP.coop-sa.bomb-requires-power-3)": "f73d4c574a0083f8020f9fc085c0c3",
        "of(ExpHP.coop-sa.different-color-options(28, 40, 25, 4402667))": "52ff771ce8[codecave:ExpHP.coop-sa.get-option-player-number]5ab91900000029c16a0b518d742428e800000000c70424eb2d4300c3",
        "of(ExpHP.coop-sa.different-color-options(104, 64, 22, 4403672))": "52ff7768e8[codecave:ExpHP.coop-sa.get-option-player-number]5ab91600000029c16a0b518d742440e800000000c70424d8314300c3"
    }
}
