{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ddc-gap.start-server": {
            "addr": "0x408558",
            "expected": "8B3D688D4A00",
            "code": "E9 [codecave:of(ExpHP.ddc-gap.start-server)] // CC"
        }
    },
    "codecaves": {
        "ExpHP.ddc-gap.corefuncs": "B8B14800 // 74B14800 // 70B14800 // F0B04800",
        "protection": 64,
        "ExpHP.ddc-gap.data": "52656C6561736553656D6170686F726500 // 43726561746553656D6170686F72654100 // 45787048502D7373612D73742D7332632E73656D00 // 45787048502D7373612D73742D6332732E73656D00 // 7500730065007200330032000000 // 4B00650072006E0065006C00330032000000 // 00000000 // 00000000 // 00000000 // 00000000 // 00000000 // 00000000 // 00000000 // 00000000 // 00000000",
        "ExpHP.ddc-gap.start-stage-server": "55 89E5 56 57 // E8[codecave:ExpHP.ddc-gap.initialize] // BF<codecave:ExpHP.ddc-gap.data> // 6A00 // 6A01 // 8B4778 // 50 // FF5770 // 6AFF // 8B477C // 50 // B8<codecave:ExpHP.ddc-gap.corefuncs> // FF500C // 5F 5E 89EC 5D // C3",
        "ExpHP.ddc-gap.start-stage-client": "55 89E5 56 57 // E8[codecave:ExpHP.ddc-gap.initialize] // BF<codecave:ExpHP.ddc-gap.data> // 6AFF // 8B4778 // 50 // B8<codecave:ExpHP.ddc-gap.corefuncs> // FF500C // 6A00 // 6A01 // 8B477C // 50 // FF5770 // 5F 5E 89EC 5D // C3",
        "ExpHP.ddc-gap.initialize-corefuncs": "BA<codecave:ExpHP.ddc-gap.corefuncs> // B904000000 // 8B02 // 8B00 // 8902 // 83C204 // 49 // 75F4 // C3",
        "ExpHP.ddc-gap.initialize": "55 89E5 56 57 // E8[codecave:ExpHP.ddc-gap.initialize-corefuncs] // BF<codecave:ExpHP.ddc-gap.data> // 8B476C // 85C0 // 754C // 8D475A // 50 // B8<codecave:ExpHP.ddc-gap.corefuncs> // FF5004 // 89C6 // 8D07 // 50 // 56 // B8<codecave:ExpHP.ddc-gap.corefuncs> // FF5008 // 894770 // 8D4711 // 50 // 56 // B8<codecave:ExpHP.ddc-gap.corefuncs> // FF5008 // 894774 // 8D4722 // 50 // E8[codecave:ExpHP.ddc-gap.create-semaphore] // 894778 // 8D4737 // 50 // E8[codecave:ExpHP.ddc-gap.create-semaphore] // 89477C // C7476C01000000 // 5F 5E 89EC 5D // C3",
        "ExpHP.ddc-gap.create-semaphore": "55 89E5 56 57 // BF<codecave:ExpHP.ddc-gap.data> // 8B4508 // 50 // 6A01 // 6A00 // 6A00 // FF5774 // 85C0 // 7509 // B8<codecave:ExpHP.ddc-gap.corefuncs> // FF10 // CD03 // 5F 5E 89EC 5D // C20400",
        "of(ExpHP.ddc-gap.start-server)": "E8[codecave:ExpHP.ddc-gap.start-stage-server] // 8B3D688D4A00 // E800000000 // C704245E854000 // C3"
    }
}