{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "base-exphp.adjust-bullet-array": "8B442404 // 8B00 // C3",
        "base-exphp.adjust-laser-array": "8B442404 // 8B00 // C3",
        "base-exphp.adjust-cancel-array": "8B442404 // 8B00 // C3",
        "ExpHP.bullet-cap.address-range": "00104000 // 38CD4800",
        "ExpHP.bullet-cap.bullet-replacements": "00040000 // 680D0000 // 00040000 // 00010100 // 01000000 // 927C4100 // 457F4100 // A8814100 // 39834100 // 92894100 // 6C8C4100 // 088F4100 // 03904100 // CC914100 // 14954100 // 5C964100 // 6D974100 // F4984100 // 019A4100 // F99A4100 // 589E4100 // 84A04100 // 6C374200 // B1374200 // 72474200 // E6494200 // 3B4C4200 // 2F4D4200 // 185B4200 // D1774200 // 00000000 // 01040000 // 00010100 // 01000000 // 72334200 // 00000000 // 00A03500 // 01000100 // 01000000 // A9634200 // 00000000 // FF030000 // 00010100 // 01000000 // A0634200 // 00000000 // 00000000",
        "ExpHP.bullet-cap.laser-replacements": "40000000 // EC040000 // 40000000 // 00010100 // 01000000 // AD334200 // 00000000 // 00000000",
        "ExpHP.bullet-cap.cancel-replacements": "4C040000 // 88020000 // 4C040000 // 00010100 // 01000000 // 4C274300 // 82274300 // B4274300 // 61294300 // 322A4300 // C03A4300 // 503B4300 // 703C4300 // 00000000 // 4D040000 // 00010100 // 01000000 // 3C264300 // 00000000 // 00000000",
        "ExpHP.bullet-cap.bullet-mgr-layout": "58F9620000000000 // 74000000 // 0000000000000000000000000000000000000000 // C0B8000000030000010000000100010000000100 // 2866360001030000010000000100010000000100 // 28A1370000000000000000000000000000000000 // 64A1370000000000000000000000000000000000EDEFCDAB // 00000000",
        "ExpHP.bullet-cap.item-mgr-layout": "705C570000000000 // 4C000000 // 0000000002030000010000000100010000000100 // 60E00A0000000000000000000000000000000000 // 7CE50A0000000000000000000000000000000000EDEFCDAB // 00000000",
        "ExpHP.bullet-cap.perf-fix-data": "00000000",
        "ExpHP.bullet-cap.pointerize-data": "58F96200 // 18B26300 // 805F9900 // 705C5700 // 705C5700 // 680D0000 // EC040000 // 88020000 // 06000000 // FC0B0000 // 64A13700 // 7CE50A00",
        "ExpHP.bullet-cap.iat-funcs": "7CD04800 // 88D14800 // 00000000 // 5CD04800 // E4D14800",
        "ExpHP.bullet-cap.corefuncs": "41D44700",
        "bullet-cap": "00004000",
        "laser-cap": "00000400",
        "cancel-cap": "000044c0",
        "bullet-cap-config.anm-search-lag-spike-size": "00002000",
        "bullet-cap-config.mof-sa-lag-spike-size": "ffffffff",
        "of(ExpHP.bullet-cap.install)": "E8[codecave:ExpHP.bullet-cap.initialize] // B8A0764200 // FFD0 // E800000000C70424E0F04200C3",
        "of(ExpHP.bullet-cap.pointerize-bullets-constructor)": "e8[codecave:ExpHP.bullet-cap.allocate-pointerized-bmgr-arrays]e800000000c70424e5334200c3",
        "of(ExpHP.bullet-cap.pointerize-items-constructor)": "e8[codecave:ExpHP.bullet-cap.allocate-pointerized-imgr-arrays]e800000000c704246f264300c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-memset)": "e8[codecave:ExpHP.bullet-cap.clear-pointerized-bullet-mgr]c3",
        "of(ExpHP.bullet-cap.pointerize-items-memset)": "e8[codecave:ExpHP.bullet-cap.clear-pointerized-item-mgr]c3",
        "of(ExpHP.bullet-cap.pointerize-item-tick)": "8b8534ffffff8b008945dcc3",
        "of(ExpHP.bullet-cap.pointerize-item-other)": "8b008945f8c745fc00000000c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(8))": "a118b263008945f8c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(232))": "a118b26300898518ffffffc3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(224))": "a118b26300898520ffffffc3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(28))": "a118b263008945e4c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(32))": "a118b263008945e0c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(12))": "a118b263008945f4c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(228))": "a118b2630089851cffffffc3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(24))": "a118b263008945e8c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-stack(20))": "a118b263008945ecc3",
        "of(ExpHP.bullet-cap.pointerize-lasers-stack(32))": "a1805f99008945e0c3",
        "of(ExpHP.bullet-cap.pointerize-lasers-stack(40))": "a1805f99008945d8c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-reg(eax))": "a118b26300c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-reg(edx))": "8b1518b26300c3",
        "of(ExpHP.bullet-cap.pointerize-bullets-reg(ecx))": "8b0d18b26300c3",
        "of(ExpHP.bullet-cap.pointerize-lasers-reg(eax))": "a1805f9900c3",
        "of(ExpHP.bullet-cap.pointerize-lasers-reg(edx))": "8b15805f9900c3",
        "of(ExpHP.bullet-cap.pointerize-lasers-reg(ecx))": "8b0d805f9900c3",
        "of(ExpHP.bullet-cap.fix-laser-cap(36, 4294845, 4295481))": "b8<codecave:laser-cap>8b000fc83945dc7c0de800000000c70424398b4100c3e800000000c70424bd884100c3",
        "of(ExpHP.bullet-cap.fix-laser-cap(44, 4295549, 4296302))": "b8<codecave:laser-cap>8b000fc83945d47c0de800000000c704246e8e4100c3e800000000c704247d8b4100c3",
        "of(ExpHP.bullet-cap.fix-laser-cap(16, 4343866, 4344196))": "b8<codecave:laser-cap>8b000fc83945f07c0de800000000c7042484494200c3e800000000c704243a484200c3",
        "of(ExpHP.bullet-cap.fix-laser-cap(16, 4344507, 4344802))": "b8<codecave:laser-cap>8b000fc83945f07c0de800000000c70424e24b4200c3e800000000c70424bb4a4200c3",
        "of(ExpHP.bullet-cap.fix-laser-cap(4, 4345440, 4346047))": "b8<codecave:laser-cap>8b000fc83945fc7c0de800000000c70424bf504200c3e800000000c70424604e4200c3",
        "of(ExpHP.bullet-cap.fix-laser-cap(8, 4350966, 4352590))": "b8<codecave:laser-cap>8b000fc83945f87c0de800000000c704244e6a4200c3e800000000c70424f6634200c3",
        "of(ExpHP.bullet-cap.fix-laser-cap(4, 4353148, 4353795))": "b8<codecave:laser-cap>8b000fc83945fc7c0de800000000c70424036f4200c3e800000000c704247c6c4200c3",
        "of(ExpHP.bullet-cap.pointerize-items-spawn(24))": "8b55e88b1201cac3",
        "of(ExpHP.bullet-cap.pointerize-items-spawn-wrap(24, eax))": "8b45e88b008945f8c3"
    },
    "binhacks": {
        "ExpHP.bullet-cap.install": {
            "addr": "0x42f0db",
            "expected": "e8c085ffff",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.install)]"
        },
        "ExpHP.bullet-cap.pointerize-bullets-constructor": {
            "addr": "0x423388",
            "expected": "8b4de883e901",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-constructor)] // CC"
        },
        "ExpHP.bullet-cap.pointerize-items-constructor": {
            "addr": "0x43264d",
            "expected": "8b4df883e901",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.pointerize-items-constructor)] // CC"
        },
        "ExpHP.bullet-cap.pointerize-bullets-memset": {
            "addr": "0x4232ef",
            "expected": "8b7dfc f3ab",
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-memset)]"
        },
        "ExpHP.bullet-cap.pointerize-items-memset": {
            "addr": "0x4275f8",
            "expected": "bf705c5700 f3ab",
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-items-memset)] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-nop": {
            "addr": "0x423410",
            "code": "9090909090"
        },
        "ExpHP.bullet-cap.pointerize-dont-clear-bmgr-on-reset": {
            "addr": "0x42778e",
            "expected": "f3ab",
            "code": "9090"
        },
        "ExpHP.bullet-cap.pointerize-item-tick": {
            "expected": "8b8534ffffff8945dc",
            "addr": [
                "0x4329a0"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-item-tick)] // 90909090"
        },
        "ExpHP.bullet-cap.pointerize-item-other": {
            "expected": "8945f8c745fc00000000",
            "addr": [
                "0x433a9c",
                "0x433b2c",
                "0x433c4c"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-item-other)] // 9090909090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(8)": {
            "expected": "c745f818b26300",
            "addr": [
                "0x417c3d",
                "0x418ee0",
                "0x4194ec",
                "0x41961c",
                "0x419897",
                "0x4199cc",
                "0x4277a9"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(8))] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(232)": {
            "expected": "c78518ffffff18b26300",
            "addr": [
                "0x417e66",
                "0x419a66",
                "0x419dd6",
                "0x41a006"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(232))] // 9090909090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(224)": {
            "expected": "c78520ffffff18b26300",
            "addr": [
                "0x418136",
                "0x4182e6"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(224))] // 9090909090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(28)": {
            "expected": "c745e418b26300",
            "addr": [
                "0x41896a"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(28))] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(32)": {
            "expected": "c745e018b26300",
            "addr": [
                "0x418c45"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(32))] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(12)": {
            "expected": "c745f418b26300",
            "addr": [
                "0x418fcc"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(12))] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(228)": {
            "expected": "c7851cffffff18b26300",
            "addr": [
                "0x419106",
                "0x419726"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(228))] // 9090909090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(24)": {
            "expected": "c745e818b26300",
            "addr": [
                "0x42474a",
                "0x4249be"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(24))] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-stack(20)": {
            "expected": "c745ec18b26300",
            "addr": [
                "0x424c0a"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-stack(20))] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-lasers-stack(32)": {
            "expected": "c745e0805f9900",
            "addr": [
                "0x41888e"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-lasers-stack(32))] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-lasers-stack(40)": {
            "expected": "c745d8805f9900",
            "addr": [
                "0x418b4e"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-lasers-stack(40))] // 9090"
        },
        "ExpHP.bullet-cap.pointerize-bullets-reg(eax)": {
            "expected": "05c0b80000",
            "addr": [
                "0x4232f7",
                "0x423380",
                "0x425a6c"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-reg(eax))]"
        },
        "ExpHP.bullet-cap.pointerize-bullets-reg(edx)": {
            "expected": "81c2c0b80000",
            "addr": [
                "0x4237a3"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-reg(edx))] // 90"
        },
        "ExpHP.bullet-cap.pointerize-bullets-reg(ecx)": {
            "expected": "81c1c0b80000",
            "addr": [
                "0x42423e"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-bullets-reg(ecx))] // 90"
        },
        "ExpHP.bullet-cap.pointerize-lasers-reg(eax)": {
            "expected": "0528663600",
            "addr": [
                "0x4233bb",
                "0x42480a",
                "0x424e0c",
                "0x426c4c"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-lasers-reg(eax))]"
        },
        "ExpHP.bullet-cap.pointerize-lasers-reg(edx)": {
            "expected": "81c228663600",
            "addr": [
                "0x424a8a"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-lasers-reg(edx))] // 90"
        },
        "ExpHP.bullet-cap.pointerize-lasers-reg(ecx)": {
            "expected": "81c128663600",
            "addr": [
                "0x4263c6"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-lasers-reg(ecx))] // 90"
        },
        "ExpHP.bullet-cap.fix-laser-cap(36, 4294845, 4295481)": {
            "expected": "837ddc400f",
            "addr": [
                "0x4188b3"
            ],
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-cap(36, 4294845, 4295481))]"
        },
        "ExpHP.bullet-cap.fix-laser-cap(44, 4295549, 4296302)": {
            "expected": "837dd4400f",
            "addr": [
                "0x418b73"
            ],
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-cap(44, 4295549, 4296302))]"
        },
        "ExpHP.bullet-cap.fix-laser-cap(16, 4343866, 4344196)": {
            "expected": "837df0400f",
            "addr": [
                "0x424830"
            ],
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-cap(16, 4343866, 4344196))]"
        },
        "ExpHP.bullet-cap.fix-laser-cap(16, 4344507, 4344802)": {
            "expected": "837df0400f",
            "addr": [
                "0x424ab1"
            ],
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-cap(16, 4344507, 4344802))]"
        },
        "ExpHP.bullet-cap.fix-laser-cap(4, 4345440, 4346047)": {
            "expected": "837dfc400f",
            "addr": [
                "0x424e56"
            ],
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-cap(4, 4345440, 4346047))]"
        },
        "ExpHP.bullet-cap.fix-laser-cap(8, 4350966, 4352590)": {
            "expected": "837df8400f",
            "addr": [
                "0x4263ec"
            ],
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-cap(8, 4350966, 4352590))]"
        },
        "ExpHP.bullet-cap.fix-laser-cap(4, 4353148, 4353795)": {
            "expected": "837dfc400f",
            "addr": [
                "0x426c72"
            ],
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-cap(4, 4353148, 4353795))]"
        },
        "ExpHP.bullet-cap.pointerize-items-spawn(24)": {
            "expected": "8b55e803d1",
            "addr": [
                "0x432708"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-items-spawn(24))]"
        },
        "ExpHP.bullet-cap.pointerize-items-spawn-wrap(24, eax)": {
            "expected": "8b45e88945f8",
            "addr": [
                "0x432795"
            ],
            "code": "E8 [codecave:of(ExpHP.bullet-cap.pointerize-items-spawn-wrap(24, eax))] // 90"
        }
    }
}
