{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.bullet-cap.address-range": "00104000 // DADA4800",
        "ExpHP.bullet-cap.bullet-replacements": "00000000 // 00000000 // 00000000",
        "ExpHP.bullet-cap.fairy-bullet-replacements": "AF000000 // C4100000 // AF000000 // 00010100 // 01000000 // 0A244100 // 292A4100 // 4D2A4100 // 92474100 // 21B64400 // 00000000 // B0000000 // 00010100 // 01000000 // 6B504100 // 00000000 // B0E10200 // 01000400 // 01000000 // 86244100 // 00000000 // 00000000",
        "ExpHP.bullet-cap.rival-bullet-replacements": "68010000 // C4100000 // 68010000 // 00010100 // 01000000 // 40244100 // 392B4100 // 622B4100 // 5FB74400 // 00000000 // 69010000 // 00010100 // 01000000 // 86504100 // 00000000 // 19E90500 // 01000400 // 01000000 // 8F244100 // 00000000 // 00000000",
        "ExpHP.bullet-cap.laser-replacements": "30000000 // 9C050000 // 30000000 // 00010100 // 01000000 // 113C4100 // 564B4100 // 00000000 // 00000000",
        "ExpHP.bullet-cap.cancel-replacements": "00000000 // 00000000 // 00000000",
        "ExpHP.bullet-cap.bullet-mgr-layout": "80000000 // 0000000000000000000000000000000000000000 // 00A9010003030000000000000100010001000100 // C02F0D0004030000000000000100010001000100 // 24D4240001030000000000000100010001000100 // 64E1250000000000000000000000000000000000 // C0E1250000000000000000000000000000000000EDEFCDAB // 9060000000000000C02F0D0001000000FFFFFFFF00000000 // 906000000000000024D4240001000000FFFFFFFF00000000 // 9060000000000000BA2C0D0001000000 // 01000000 // E9234100 // B8244100 // 00000000 // 90600000000000001ED1240001000000 // 01000000 // F0234100 // BF244100 // 00000000 // 9160000064E12500C0E12500 // 01000000 // 2F474100 // A0474100 // 35474100 // A8474100 // 29474100 // 8B474100 // 98474100 // 9E304100 // 98324100 // 554F4100 // 604F4100 // 684F4100 // B5504100 // 734F4100 // 9A414100 // 6D514100 // 76514100 // 86514100 // 89414100 // BD514100 // C9514100 // EC3B4100 // 13474100 // 5C514100 // 81E24100 // 11314100 // E1314100 // 89334100 // 39384100 // 203E4100 // 6C474100 // 464A4100 // 6B4A4100 // BF4A4100 // 3F4B4100 // 744D4100 // DB4D4100 // D34E4100 // 4A514100 // 62514100 // B2234100 // F33D4100 // 80474100 // 144B4100 // AC234100 // A6234100 // A0234100 // 9A234100 // 94234100 // E2234100 // A5244100 // 7C294100 // F6234100 // B1244100 // 622A4100 // FC234100 // C5244100 // 94C54000 // 7BC64000 // 29254100 // 59254100 // 6F254100 // D22E4100 // 4D2F4100 // 582F4100 // E4324100 // 02334100 // 20334100 // 733E4100 // A03E4100 // B13E4100 // CB3E4100 // DD3E4100 // F73E4100 // 86424100 // 0ADC4100 // 00000000 // 9060000000000000C0E1250001000000 // 01000000 // EC504100 // 19514100 // 00000000 // 9060000000000000C0E1250004000000 // 01000000 // C9234100 // 00000000 // 9060000000A9010060C32400C4100000 // 01000000 // 4DC54000 // 4DC74000 // 304B4100 // 00000000 // 00000000",
        "ExpHP.bullet-cap.item-mgr-layout": "1C000000 // 0000000000000000000000000000000000000000EDEFCDAB // 00000000",
        "ExpHP.bullet-cap.perf-fix-data": "00000000",
        "ExpHP.bullet-cap.iat-funcs": "8CE04800 // DCE04800 // 00000000 // D8E04800 // 10E24800",
        "ExpHP.bullet-cap.corefuncs": "4EB24700",
        "bullet-cap": "ffff ffff",
        "laser-cap": "ffff ffff",
        "cancel-cap": "ffff ffff",
        "bullet-cap-config.anm-search-lag-spike-size": "ffff ffff",
        "bullet-cap-config.mof-sa-lag-spike-size": "ffff ffff",
        "of(ExpHP.bullet-cap.install)": "e8[codecave:ExpHP.bullet-cap.initialize]bec47d4a00e800000000c704240eb24100c3",
        "of(ExpHP.bullet-cap.fix-laser-cmp)": "506801030000e8[codecave:ExpHP.bullet-cap.get-new-cap]89c15839c87c0de800000000c70424d6324100c3e800000000c70424c0324100c3",
        "of(ExpHP.bullet-cap.fix-laser-push)": "6801030000e8[codecave:ExpHP.bullet-cap.get-new-cap]50689c050000e800000000c70424a7504100c3"
    },
    "options": {
        "bullet-cap.bullet-cap": {
            "type": "i32",
            "val": -1
        },
        "bullet-cap.laser-cap": {
            "type": "i32",
            "val": 768
        },
        "bullet-cap.cancel-cap": {
            "type": "i32",
            "val": -1
        },
        "bullet-cap.fairy-bullet-cap": {
            "type": "i32",
            "val": 2800
        },
        "bullet-cap.rival-bullet-cap": {
            "type": "i32",
            "val": 5760
        },
        "bullet-cap.anm-search-lag-spike-size": {
            "type": "i32",
            "val": 8192
        }
    },
    "binhacks": {
        "ExpHP.bullet-cap.install": {
            "addr": "0x41b209",
            "expected": "bec47d4a00",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.install)]"
        },
        "ExpHP.bullet-cap.fix-laser-cmp": {
            "addr": "0x4132d1",
            "expected": "83f830 // 7cea",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-cmp)]"
        },
        "ExpHP.bullet-cap.fix-laser-push": {
            "addr": "0x4150a0",
            "expected": "6a30689c050000",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.fix-laser-push)] // CCCC"
        }
    }
}
