{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.bullet-cap.install": {
            "addr": "0x420ec8",
            "expected": "e883b20200",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.install)]"
        }
    },
    "codecaves": {
        "ExpHP.bullet-cap.address-range": "00104000 // 815A4600",
        "ExpHP.bullet-cap.bullet-data": "D0070000 // F0070000",
        "ExpHP.bullet-cap.counts-to-replace": "D0070000 // 09564100 // 7EBD4400 // 00000000 // D1070000 // 00000000 // 00000000",
        "ExpHP.bullet-cap.offsets-to-replace": "A6073E00 // 01000000 // 00000000 // 500B3E00 // 01000000 // 00000000 // 540B3E00 // 01000000 // 00000000 // D5820F00 // 04000000 // 00000000 // BC820F00 // 04000000 // 00000000 // 00000000",
        "ExpHP.bullet-cap.iat-funcs": "DCFA4500 // 98614600 // 00000000 // 58614600",
        "of(ExpHP.bullet-cap.install)": "E8[codecave:ExpHP.bullet-cap.initialize] // B850C14400 // FFD0 // E800000000 // C70424CD0E4200 // C3"
    }
}