{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.bullet-cap.install": {
            "addr": "0x42a51e",
            "expected": "be703a4c00",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.install)]"
        }
    },
    "codecaves": {
        "ExpHP.bullet-cap.iat-funcs": "B8B14800 // 74B14800 // 70B14800",
        "ExpHP.bullet-cap.bullet-count-blacklist": "90C34100 // 53904500 // 08B84600 // 00000000",
        "ExpHP.bullet-cap.offsets-to-adjust": "16D24600 // 00000000 // 74D64600 // 00000000 // 78D64600 // 00000000 // 10D64600 // 00000000 // 00000000",
        "ExpHP.bullet-cap.new-bullet-count": "B80B0000",
        "ExpHP.bullet-cap.bullet-count-plusone-blacklist": "00000000",
        "ExpHP.bullet-cap.initialize": "55 89E5 56 57 // 83EC18 // A1<codecave:ExpHP.bullet-cap.new-bullet-count> // 8945FC // C745F8D0070000 // 68<codecave:ExpHP.bullet-cap.bullet-count-blacklist> // 6A04 // 8D45FC // 50 // 8D45F8 // 50 // 6815AE4800 // 6800104000 // E8[codecave:ExpHP.bullet-cap.search-n-replace] // 8B45FC // 8945EC // 8B45F8 // 8945E8 // FF45EC // FF45E8 // 68<codecave:ExpHP.bullet-cap.bullet-count-plusone-blacklist> // 6A04 // 8D45EC // 50 // 8D45E8 // 50 // 6815AE4800 // 6800104000 // E8[codecave:ExpHP.bullet-cap.search-n-replace] // B8<codecave:ExpHP.bullet-cap.offsets-to-adjust> // 8945F4 // 83C004 // 8945F0 // 8B45F4 // 8B00 // 85C0 // 7428 // FF75F0 // 50 // FF75FC // E8[codecave:ExpHP.bullet-cap.adjust-bullet-mgr-offset] // 8B4DF0 // 8B01 // 85C0 // 7405 // 83C104 // EBF5 // 83C104 // 894DF4 // 83C104 // 894DF0 // EBCF // 5F 5E 89EC 5D // C3",
        "ExpHP.bullet-cap.adjust-bullet-mgr-offset": "55 89E5 56 57 // 83EC04 // 8B4508 // 2DD0070000 // 69C010090000 // 03450C // 8945FC // FF7510 // 6A04 // 8D45FC // 50 // 8D450C // 50 // 6815AE4800 // 6800104000 // E8[codecave:ExpHP.bullet-cap.search-n-replace] // 5F 5E 89EC 5D // C20C00",
        "ExpHP.bullet-cap.search-n-replace": "55 89E5 56 57 // 8B4508 // 034518 // 3B450C // 7D35 // FF7518 // FF7510 // FF7508 // E8[codecave:ExpHP.bullet-cap.mem-compare] // 85C0 // 751E // 8B4508 // 8B4D1C // 3B01 // 7410 // FF7518 // FF7514 // FF7508 // E8[codecave:ExpHP.bullet-cap.memcpy-or-bust] // EB04 // 83451C04 // FF4508 // EBC0 // 8B451C // 8B00 // 85C0 // 7402 // CD03 // 5F 5E 89EC 5D // C21800",
        "ExpHP.bullet-cap.mem-compare": "55 89E5 56 57 // 8B7D08 // 8B750C // 8B4D10 // 31C0 // 4E // 4F // 46 // 47 // 49 // 7806 // 8A06 // 2A07 // 74F5 // 5F 5E 89EC 5D // C20C00",
        "ExpHP.bullet-cap.memcpy-or-bust": "55 89E5 56 57 // 83EC08 // E8[codecave:ExpHP.bullet-cap.get-VirtualProtect] // 8945FC // 8D45F8 // 50 // 6A40 // FF7510 // FF7508 // FF55FC // 8B4D10 // 8B750C // 8B7D08 // F3A4 // 8D45F8 // 50 // FF75F8 // FF7510 // FF7508 // FF55FC // 5F 5E 89EC 5D // C20C00",
        "ExpHP.bullet-cap.data": "4B00650072006E0065006C00330032000000 // 5669727475616C50726F7465637400",
        "ExpHP.bullet-cap.get-VirtualProtect": "55 89E5 56 57 // B8<codecave:ExpHP.bullet-cap.data> // 8D00 // 50 // B8<codecave:ExpHP.bullet-cap.iat-funcs> // 8B4004 // FF10 // 85C0 // 7420 // 89C1 // B8<codecave:ExpHP.bullet-cap.data> // 8D4012 // 50 // 51 // B8<codecave:ExpHP.bullet-cap.iat-funcs> // 8B4008 // FF10 // 85C0 // 7406 // 5F 5E 89EC 5D // C3 // B8<codecave:ExpHP.bullet-cap.iat-funcs> // 8B00 // FF10 // CD03",
        "of(ExpHP.bullet-cap.install)": "E8[codecave:ExpHP.bullet-cap.initialize] // BE703A4C00 // E800000000 // C7042423A54200 // C3"
    }
}