{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.bullet-cap.address-range": "00104000 // 3C0F4B00",
        "ExpHP.bullet-cap.bullet-replacements": "D0070000 // F4130000 // D0070000 // 00010100 // FFFFFFFF // 860E4300 // 3D934300 // 00000000 // D1070000 // 00010100 // 01000000 // 3E604100 // EA644100 // 5C654100 // 00000000 // 34F69B00 // 01000100 // 01000000 // 96624100 // 00000000 // 00000000",
        "ExpHP.bullet-cap.laser-replacements": "00010000 // 00000000 // 00010000 // 00010100 // 01000000 // 61A74300 // D2CB4300 // 40D94300 // AEEB4300 // 35F84300 // 3E2E4400 // 00000000 // 00000000",
        "ExpHP.bullet-cap.cancel-replacements": "00100000 // 180C0000 // 58120000 // 00010100 // 01000000 // 6E824300 // 09844300 // 7D844300 // A38D4300 // 46964300 // DE9B4300 // 00000000 // 40D8DD00 // 01000100 // 01000000 // C6D84100 // 00000000 // 00100000 // 00010100 // 01000000 // 78D94100 // 00000000 // 00000000",
        "ExpHP.bullet-cap.bullet-mgr-layout": "58000000 // 0000000000000000000000000000000000000000 // 8C00000000030000000000000100010001000100 // C0F69B0000000000000000000000000000000000 // D0F69B0000000000000000000000000000000000EDEFCDAB // 9060000000000000DAEE9B0001000000FFFFFFFF00000000 // 9060000000000000C0F69B0001000000FFFFFFFF00000000 // 9060000000000000C4F69B0001000000FFFFFFFF00000000 // 9060000000000000C8F69B0001000000FFFFFFFF00000000 // 9060000000000000CCF69B0001000000FFFFFFFF00000000 // 9060000000000000D0F69B0001000000FFFFFFFF00000000 // 00000000",
        "ExpHP.bullet-cap.item-mgr-layout": "58000000 // 0000000000000000000000000000000000000000 // 54581C0002030000000000000100010001000100 // 54D8DD0000000000000000000000000000000000 // 88D8DD0000000000000000000000000000000000EDEFCDAB // 906000000000000054D8DD0001000000FFFFFFFF00000000 // 906000000000000058D8DD0001000000FFFFFFFF00000000 // 90600000000000005CD8DD0001000000FFFFFFFF00000000 // 906000000000000060D8DD0001000000FFFFFFFF00000000 // 906000000000000064D8DD0001000000FFFFFFFF00000000 // 906000000000000068D8DD0001000000FFFFFFFF00000000 // 90600000000000006CD8DD0001000000FFFFFFFF00000000 // 906000000000000070D8DD0001000000FFFFFFFF00000000 // 906000000000000074D8DD0001000000FFFFFFFF00000000 // 906000000000000078D8DD0001000000FFFFFFFF00000000 // 90600000000000007CD8DD0001000000FFFFFFFF00000000 // 906000000000000080D8DD0001000000FFFFFFFF00000000 // 906000000000000084D8DD0001000000FFFFFFFF00000000 // 906000000000000088D8DD0001000000FFFFFFFF00000000 // 00000000",
        "ExpHP.bullet-cap.perf-fix-data": "00000000",
        "ExpHP.bullet-cap.iat-funcs": "94104B00 // 00000000 // 38114B00 // F8104B00 // 50124B00",
        "ExpHP.bullet-cap.corefuncs": "AF544800",
        "bullet-cap": "ffff ffff",
        "laser-cap": "ffff ffff",
        "cancel-cap": "ffff ffff",
        "bullet-cap-config.anm-search-lag-spike-size": "ffff ffff",
        "bullet-cap-config.mof-sa-lag-spike-size": "ffff ffff",
        "of(ExpHP.bullet-cap.install)": "51e8[codecave:ExpHP.bullet-cap.initialize]59b8005b4400ffd0e800000000c70424ca654300c3"
    },
    "options": {
        "bullet-cap.bullet-cap": {
            "type": "i32",
            "val": 32000
        },
        "bullet-cap.laser-cap": {
            "type": "i32",
            "val": 4096
        },
        "bullet-cap.cancel-cap": {
            "type": "i32",
            "val": 65536
        },
        "bullet-cap.fairy-bullet-cap": {
            "type": "i32",
            "val": -1
        },
        "bullet-cap.rival-bullet-cap": {
            "type": "i32",
            "val": -1
        },
        "bullet-cap.anm-search-lag-spike-size": {
            "type": "i32",
            "val": 8192
        }
    },
    "binhacks": {
        "ExpHP.bullet-cap.install": {
            "addr": "0x4365c5",
            "expected": "e836f50000",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.install)]"
        }
    }
}
