{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.bullet-cap.address-range": "00104000 // 8C794B00",
        "ExpHP.bullet-cap.bullet-replacements": "D0070000 // F4130000 // D0070000 // 00010100 // 01000000 // 2A254100 // 4A264100 // 78764100 // 437A4100 // DA7C4100 // 00000000 // D1070000 // 00010100 // 01000000 // BE234100 // 5A284100 // CC284100 // 00000000 // 34F69B00 // 01000100 // 01000000 // 16264100 // 00000000 // 00000000",
        "ExpHP.bullet-cap.laser-replacements": "00010000 // 00000000 // 00010000 // 00010100 // 01000000 // 71904300 // DFB74300 // 30C54300 // 26DA4300 // 5BE74300 // 00000000 // 00000000",
        "ExpHP.bullet-cap.cancel-replacements": "00100000 // 1C0C0000 // 58120000 // 00010100 // 01000000 // FE4D4300 // 994F4300 // 0D504300 // E9594300 // C65E4300 // 4E644300 // 00000000 // A021DE00 // 01000100 // 01000000 // 06994100 // 00000000 // 00100000 // 00010100 // 01000000 // B8994100 // 00000000 // 00000000",
        "ExpHP.bullet-cap.bullet-mgr-layout": "58000000 // 0000000000000000000000000000000000000000 // 8C00000000030000000000000100010001000100 // C0F69B0000000000000000000000000000000000 // D0F69B0000000000000000000000000000000000EDEFCDAB // 9060000000000000DAEE9B0001000000FFFFFFFF00000000 // 9060000000000000C0F69B0001000000FFFFFFFF00000000 // 9060000000000000C4F69B0001000000FFFFFFFF00000000 // 9060000000000000C8F69B0001000000FFFFFFFF00000000 // 9060000000000000CCF69B0001000000FFFFFFFF00000000 // 9060000000000000D0F69B0001000000FFFFFFFF00000000 // 00000000",
        "ExpHP.bullet-cap.item-mgr-layout": "58000000 // 0000000000000000000000000000000000000000 // 54581C0002030000000000000100010001000100 // B421DE0000000000000000000000000000000000 // E821DE0000000000000000000000000000000000EDEFCDAB // 91600000B421DE00E921DE00 // 01000000 // 35994100 // A2994100 // 42604300 // 19514300 // C0594300 // 85734100 // BE734100 // E8734100 // 05744100 // 11994100 // 04D74100 // 20D84100 // A6174200 // 75604300 // 93604300 // AF604300 // 3BF74400 // 0F514300 // 68604300 // A4624300 // 1C994100 // 5C604300 // D7614300 // 26994100 // 114E4300 // E64F4300 // 20504300 // 00000000 // 00000000",
        "ExpHP.bullet-cap.perf-fix-data": "00000000",
        "ExpHP.bullet-cap.iat-funcs": "94804B00 // 00000000 // 2C814B00 // F8804B00 // 48824B00",
        "ExpHP.bullet-cap.corefuncs": "97A64800",
        "bullet-cap": "ffff ffff",
        "laser-cap": "ffff ffff",
        "cancel-cap": "ffff ffff",
        "bullet-cap-config.anm-search-lag-spike-size": "ffff ffff",
        "bullet-cap-config.mof-sa-lag-spike-size": "ffff ffff",
        "of(ExpHP.bullet-cap.install)": "51e8[codecave:ExpHP.bullet-cap.initialize]59b8d04a4400ffd0e800000000c704246f2f4300c3"
    },
    "options": {
        "bullet-cap.bullet-cap": {
            "type": "i32",
            "val": 32000
        },
        "bullet-cap.laser-cap": {
            "type": "i32",
            "val": 4096
        },
        "bullet-cap.cancel-cap": {
            "type": "i32",
            "val": 65536
        },
        "bullet-cap.fairy-bullet-cap": {
            "type": "i32",
            "val": -1
        },
        "bullet-cap.rival-bullet-cap": {
            "type": "i32",
            "val": -1
        },
        "bullet-cap.anm-search-lag-spike-size": {
            "type": "i32",
            "val": 8192
        }
    },
    "binhacks": {
        "ExpHP.bullet-cap.install": {
            "addr": "0x432f6a",
            "expected": "e8611b0100",
            "code": "E9 [codecave:of(ExpHP.bullet-cap.install)]"
        }
    }
}
