{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "protection": "0x40",
        "ExpHP.anm-buffers.game-data": "FC050000 // AC494700",
        "of(ExpHP.anm-buffers.alloc)": "E8[codecave:ExpHP.anm-buffers.new-alloc-vm] // E800000000C70424FCF64600C3",
        "of(ExpHP.anm-buffers.dealloc)": "E8[codecave:ExpHP.anm-buffers.new-dealloc-vm] // E800000000C7042451EC4600C3"
    },
    "binhacks": {
        "ExpHP.anm-buffers.alloc": {
            "addr": "0x46f6ef",
            "expected": "68fc050000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.alloc)]"
        },
        "ExpHP.anm-buffers.dealloc": {
            "addr": "0x46ec48",
            "expected": "50e864930000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.dealloc)] // CC"
        }
    }
}
