{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.mouse.binhack": {
            "addr": "0x44d7a8",
            "expected": "81fa00a4ffff",
            "code": "E9 [codecave:of(ExpHP.mouse.binhack)] // CC"
        }
    },
    "codecaves": {
        "protection": 64,
        "ExpHP.mouse.data": "00000000 // 00000000",
        "ExpHP.mouse.strings": "7500730065007200330032000000 // 476574437572736F72506F7300 // 53637265656E546F436C69656E7400",
        "ExpHP.mouse.res-data": "0000803F2000000010000000A0010000D0010000 // 0000C03F300000001800000070020000B8020000 // 00000040400000002000000040030000A0030000",
        "ExpHP.mouse.get-mouse-pos-subpixels": "55 89E5 56 57 // 53 // E8[codecave:ExpHP.mouse.initialize] // BB<codecave:ExpHP.mouse.data> // BE<codecave:ExpHP.mouse.res-data> // E8[codecave:ExpHP.mouse.get-resolution-index] // 6BC014 // 01C6 // 8B7D08 // 57 // FF5304 // 57 // FF35185A4F00 // FF13 // 8B4604 // 2907 // 8B4608 // 294704 // F30F2A07 // F30F2A4F04 // F30F1016 // F30F5EC2 // F30F5ECA // B8C0000000 // F30F2AD0 // F30F5CC2 // B800000000 // F30F2AD0 // F30F5CCA // B880000000 // F30F2AD0 // F30F59C2 // F30F59CA // F30F2DC0 // 8907 // F30F2DC1 // 894704 // 5B // 5F 5E 89EC 5D // C20400",
        "ExpHP.mouse.initialize": "55 89E5 56 57 // 53 // BE<codecave:ExpHP.mouse.strings> // BF<codecave:ExpHP.mouse.data> // 837F0400 // 7526 // 8D06 // 50 // FF1538114B00 // 89C3 // 8D460E // 50 // 53 // FF15F8104B00 // 894704 // 8D461B // 50 // 53 // FF15F8104B00 // 8907 // 5B // 5F 5E 89EC 5D // C3",
        "ExpHP.mouse.get-resolution-index": "A158904D00 // 3DE0010000 // 740E // 3DD0020000 // 740D // 3DC0030000 // 740C // B800000000 // C3 // B801000000 // C3 // B802000000 // C3",
        "of(ExpHP.mouse.binhack)": "56 // 8DB7EC050000 // 56 // E8[codecave:ExpHP.mouse.get-mouse-pos-subpixels] // 8B16 // 8B4E04 // 5E // 81FA00A4FFFF // E800000000 // C70424AED74400 // C3"
    }
}
