{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.ultra-increase": {
            "expected": "b9d8da4b00",
            "addr": [
                "0x424d5d"
            ],
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-increase)]"
        },
        "ExpHP.ultra.ultra-decrease": {
            "expected": "8b88c4000000",
            "addr": [
                "0x424dd1"
            ],
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-decrease)] // 90"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.ultra-increase)": "8b450866c1a0bc0000000266c1a0be00000002b9d8da4b00c3",
        "of(ExpHP.ultra.ultra-decrease)": "66c1a8bc0000000266c1a8be000000028b88c4000000c3"
    }
}
