{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.patch-1": {
            "addr": "0x424d5d",
            "expected": "b9d8da4b00",
            "code": "E8 [codecave:of(ExpHP.ultra.patch-1)]"
        },
        "ExpHP.ultra.patch-2": {
            "addr": "0x424dce",
            "expected": "8b45088b88c4000000",
            "code": "E8 [codecave:of(ExpHP.ultra.patch-2)] // 90909090"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.patch-1)": "8B4508 // 66C1A0BE00000002 // 66C1A0BC00000002 // B9D8DA4B00 // C3",
        "of(ExpHP.ultra.patch-2)": "8B4508 // 66C1A8BE00000002 // 66C1A8BC00000002 // 8B4508 // 8B88C4000000 // C3"
    }
}
