{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.ultra-decrease": {
            "addr": [
                "0x430ee0"
            ],
            "expected": "8b88fc010000",
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-decrease)] // 90"
        },
        "ExpHP.ultra.ultra-increase": {
            "addr": [
                "0x430e6c"
            ],
            "expected": "b9f85e7d01",
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-increase)]"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.ultra-decrease)": "66c1a8f40100000266c1a8f6010000028b88fc010000c3",
        "of(ExpHP.ultra.ultra-increase)": "8b450866c1a0f40100000266c1a0f601000002b9f85e7d01c3"
    }
}
