{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.patch-1": {
            "addr": "0x430e6c",
            "expected": "b9f85e7d01",
            "code": "E9 [codecave:of(ExpHP.ultra.patch-1)]"
        },
        "ExpHP.ultra.patch-2": {
            "addr": "0x430edd",
            "expected": "8b45088b88fc010000",
            "code": "E9 [codecave:of(ExpHP.ultra.patch-2)] // CCCCCCCC"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.patch-1)": "8B4508 // 66C1A0F601000002 // 66C1A0F401000002 // B9F85E7D01 // E800000000C70424 710e4300 C3",
        "of(ExpHP.ultra.patch-2)": "8B4508 // 66C1A8F601000002 // 66C1A8F401000002 // 8B4508 // 8B88FC010000 // E800000000C70424 e60e4300 C3"
    }
}
