{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.ultra-increase": {
            "expected": "8b8990e12500",
            "addr": [
                "0x41310f",
                "0x4131df"
            ],
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-increase)] // 90"
        },
        "ExpHP.ultra.ultra-decrease": {
            "expected": "8b86fc010000",
            "addr": [
                "0x413190",
                "0x413260"
            ],
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-decrease)] // 90"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.ultra-increase)": "8b450866c1a0f40100000266c1a0f6010000028b8990e12500c3",
        "of(ExpHP.ultra.ultra-decrease)": "66c1aef40100000266c1aef6010000028b86fc010000c3"
    }
}
