{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.ultra-increase": {
            "expected": "6683bef601000000",
            "addr": [
                "0x413122",
                "0x4131f2"
            ],
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-increase)] // 909090"
        },
        "ExpHP.ultra.ultra-decrease": {
            "expected": "8b86fc010000",
            "addr": [
                "0x413190",
                "0x413260"
            ],
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-decrease)] // 90"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.ultra-increase)": "66c1a6f40100000266c1a6f6010000026683bef601000000c3",
        "of(ExpHP.ultra.ultra-decrease)": "66c1aef40100000266c1aef6010000028b86fc010000c3"
    }
}
