{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.th15-1": {
            "addr": "0x41c646",
            "expected": "f30f11442410",
            "code": "E9 [codecave:of(ExpHP.ultra.th15-1)] // CC"
        },
        "ExpHP.ultra.th15-2": {
            "addr": "0x414e93",
            "expected": "f6876c03000020",
            "code": "E9 [codecave:of(ExpHP.ultra.th15-2)] // CCCC"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.th15-1)": "F30F11442410 // 66C1A76403000002 // 66C1A76603000002 // E800000000C704244CC64100C3",
        "of(ExpHP.ultra.th15-2)": "66C1AF6403000002 // 66C1AF6603000002 // F6876C03000020 // E800000000C70424BAC64100C3"
    }
}
