{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.ultra-decrease": {
            "addr": [
                "0x412b83"
            ],
            "expected": "f6876c03000020",
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-decrease)] // 9090"
        },
        "ExpHP.ultra.ultra-increase": {
            "addr": [
                "0x412b16"
            ],
            "expected": "f30f11442410",
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-increase)] // 90"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.ultra-decrease)": "66c1af640300000266c1af6603000002f6876c03000020c3",
        "of(ExpHP.ultra.ultra-increase)": "83c404f30f1144241066c1a7640300000266c1a7660300000283ec04c3"
    }
}
