{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.th16-1": {
            "addr": "0x414e26",
            "expected": "f30f11442410",
            "code": "E9 [codecave:of(ExpHP.ultra.th16-1)] // CC"
        },
        "ExpHP.ultra.th16-2": {
            "addr": "0x414e93",
            "expected": "f6876c03000020",
            "code": "E9 [codecave:of(ExpHP.ultra.th16-2)] // CCCC"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.th16-1)": "F30F11442410 // 66C1A76403000002 // 66C1A76603000002 // E800000000C704242C4E4100C3",
        "of(ExpHP.ultra.th16-2)": "66C1AF6403000002 // 66C1AF6603000002 // F6876C03000020 // E800000000C704249A4E4100C3"
    }
}
