{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.ultra.ultra-increase": {
            "expected": "f30f11442410",
            "addr": [
                "0x4207e6"
            ],
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-increase)] // 90"
        },
        "ExpHP.ultra.ultra-decrease": {
            "expected": "f6877404000020",
            "addr": [
                "0x420853"
            ],
            "code": "E8 [codecave:of(ExpHP.ultra.ultra-decrease)] // 9090"
        }
    },
    "codecaves": {
        "of(ExpHP.ultra.ultra-increase)": "83c404f30f1144241066c1a76c0400000466c1a76e0400000483ec04c3",
        "of(ExpHP.ultra.ultra-decrease)": "66c1af6c0400000466c1af6e04000004f6877404000020c3"
    }
}
