{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "TH17Perf ~ Prepare compact array in AnmManager::on_tick_world": {
            "addr": "0x47591d",
            "expected": "8b8c24d4000000",
            "code": "E9 [codecave:of(TH17Perf ~ Prepare compact array in AnmManager::on_tick_world)] // CCCC"
        },
        "TH17Perf ~ Use compact array head": {
            "addr": "0x475bc2",
            "expected": "8b86dc060000 // 8B5D08 // 85C0",
            "code": "E8 [codecave:ExpHP.TH17Perf.get-compact-array] // 8B5D08 // 833800"
        },
        "TH17Perf ~ Use compact array fields": {
            "addr": "0x475bd0",
            "expected": "8b38 // 8b5804 // f6873405000060",
            "code": "8B38 // 89C3 // 83C30C // F6400860 // 90"
        },
        "TH17Perf ~ Advance to next in compact array": {
            "addr": "0x475c00",
            "expected": "8b c3 // 85 db // 75 ca",
            "code": "E9 [codecave:of(TH17Perf ~ Advance to next in compact array)] // CC"
        },
        "TH17Perf ~ Use layer from compact array": {
            "addr": "0x475bde",
            "expected": "8b5718",
            "code": "8B5004"
        }
    },
    "codecaves": {
        "ExpHP.TH17Perf.prepare-compact-array": "55 89E5 56 57 // 8B35209A5000 // 89F7 // 8BBEDC060000 // E8 [codecave:ExpHP.TH17Perf.get-compact-array] // 89C6 // 85FF // 741B // 8B0F // 890E // 8B4118 // 894604 // 8B8134050000 // 894608 // 8B7F04 // 83C60C // EBE1 // C70600000000 // 5F 5E 89EC 5D // C3",
        "ExpHP.TH17Perf.get-compact-array": "55 89E5 56 57 // 8B0D209A5000 // 8B81400AC901 // 85C0 // 751B // 6800003300 // B850B24700 // FFD0 // 83C404 // 8B0D209A5000 // 8981400AC901 // 5F 5E 89EC 5D // C3",
        "of(TH17Perf ~ Prepare compact array in AnmManager::on_tick_world)": "E8 [codecave:ExpHP.TH17Perf.prepare-compact-array] // 8b8c24d4000000 // E800000000 // C7042424594700 // C3",
        "of(TH17Perf ~ Advance to next in compact array)": "89D8 // 8B1B // 85DB // 740D // E800000000 // C70424D05B4700 // C3 // E800000000 // C70424065C4700 // C3"
    }
}
