{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.sprite-death-fix.hack": {
            "addr": "0x442fe4",
            "expected": "8bb8ccda7200",
            "code": "E9 [codecave:of(ExpHP.sprite-death-fix.hack)] // CC"
        }
    },
    "codecaves": {
        "of(ExpHP.sprite-death-fix.hack)": "52 // 8B35101C4900 // 8DB8CCDA7200 // 8B07 // 05A8000000 // 39F8 // 7C19 // B8502F4400 // FFD0 // 8D86CCDA3A00 // 8986CCDA7200 // 8986D0DA7200 // 5A // A1101C4900 // 8BB8CCDA7200 // E800000000 // C70424EA2F4400 // C3"
    }
}
