{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.sprite-death-fix.hack": {
            "addr": "0x443079",
            "expected": "33c05bc3cc",
            "code": "E9 [codecave:of(ExpHP.sprite-death-fix.hack)]"
        }
    },
    "codecaves": {
        "of(ExpHP.sprite-death-fix.hack)": "56 // 8B35101C4900 // B8502F4400 // FFD0 // 8D86CCDA3A00 // 8986CCDA7200 // 8986D0DA7200 // 5E // 5B // C3"
    }
}