{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.sprite-death-fix.hack": {
            "addr": "0x44fda4",
            "expected": "8bb824567b00",
            "code": "E9 [codecave:of(ExpHP.sprite-death-fix.hack)] // CC"
        }
    },
    "codecaves": {
        "of(ExpHP.sprite-death-fix.hack)": "52 // 8B3568324C00 // 8DB824567B00 // 8B07 // 05A8000000 // 39F8 // 7C19 // B810FD4400 // FFD0 // 8D8624564300 // 898624567B00 // 898628567B00 // 5A // A168324C00 // 8BB824567B00 // E800000000 // C70424AAFD4400 // C3"
    }
}
