{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.sprite-death-fix.hack": {
            "addr": "0x45a4a4",
            "expected": "8bb8a4568300",
            "code": "E9 [codecave:of(ExpHP.sprite-death-fix.hack)] // CC"
        }
    },
    "codecaves": {
        "of(ExpHP.sprite-death-fix.hack)": "52 // 8B35CCE84C00 // 8DB8A4568300 // 8B07 // 05A8000000 // 39F8 // 7C19 // B8C0A34500 // FFD0 // 8D86A4564B00 // 8986A4568300 // 8986A8568300 // 5A // A1CCE84C00 // 8BB8A4568300 // E800000000 // C70424AAA44500 // C3"
    }
}
