{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.sprite-death-fix.hack": {
            "addr": "0x458fb4",
            "expected": "8bb8acd68300",
            "code": "E9 [codecave:of(ExpHP.sprite-death-fix.hack)] // CC"
        }
    },
    "codecaves": {
        "of(ExpHP.sprite-death-fix.hack)": "52 // 8B35B40C4D00 // 8DB8ACD68300 // 8B07 // 05A8000000 // 39F8 // 7C19 // B8D08E4500 // FFD0 // 8D86ACD64B00 // 8986ACD68300 // 8986B0D68300 // 5A // A1B40C4D00 // 8BB8ACD68300 // E800000000 // C70424BA8F4500 // C3"
    }
}
