{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.sprite-death-fix.hack": {
            "addr": "0x45f043",
            "expected": "8bb8f0968600",
            "code": "E9 [codecave:of(ExpHP.sprite-death-fix.hack)] // CC"
        }
    },
    "codecaves": {
        "of(ExpHP.sprite-death-fix.hack)": "52 // 8B35502E4D00 // 8DB8F0968600 // 8B07 // 05A8000000 // 39F8 // 7C19 // B860EF4500 // FFD0 // 8D86F0964E00 // 8986F0968600 // 8986F4968600 // 5A // A1502E4D00 // 8BB8F0968600 // E800000000C70424 49f04500 C3"
    }
}
