{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.sprite-death-fix.hack": {
            "addr": "0x467a83",
            "expected": "8bb8f481ef00",
            "code": "E9 [codecave:of(ExpHP.sprite-death-fix.hack)] // CC"
        }
    },
    "codecaves": {
        "of(ExpHP.sprite-death-fix.hack)": "52 // 8B3588C64D00 // 8DB8F481EF00 // 8B07 // 05A8000000 // 39F8 // 7C19 // B8A0794600 // FFD0 // 8D86F481B700 // 8986F481EF00 // 8986F881EF00 // 5A // A188C64D00 // 8BB8F481EF00 // E800000000C70424 897a4600 C3"
    }
}
