{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "TH17 Split C and Control - Other Branch - C is not 0x200": {
            "addr": "0x401d0f",
            "expected": "0bc8",
            "code": "66 90"
        },
        "TH17 Split C and Control - Other Branch - C is 0x4": {
            "addr": "0x401df3",
            "expected": "25a0000000",
            "code": "E9 [codecave:of(TH17 Split C and Control - Other Branch - C is 0x4)]"
        },
        "TH17 Split C and Control - GetKeyboardState branch - C is not 0x200": {
            "addr": "0x401b7d",
            "expected": "0bc8",
            "code": "66 90"
        },
        "TH17 Split C and Control - GetKeyboardState branch - C is 0x4": {
            "addr": "0x401c57",
            "expected": "83e050 // e999010000",
            "code": "E9 [codecave:of(TH17 Split C and Control - GetKeyboardState branch - C is 0x4)] // CCCCCC"
        }
    },
    "codecaves": {
        "of(TH17 Split C and Control - Other Branch - C is 0x4)": "25 a0000000 // 0bf0 // 0bfe // 0fb64424 36 // c1e8 05 // 09c7 // E8 00000000 // C70424 FC1D4000 // C3",
        "of(TH17 Split C and Control - GetKeyboardState branch - C is 0x4)": "83e0 50 // 0bf0 // 0bfe // 0fb64424 4b // c1e8 05 // 09c7 // E8 00000000 // C70424 FC1D4000 // C3"
    }
}