{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x4240e4",
            "expected": "b900b94700",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    },
    "codecaves": {
        "ExpHP.debug-counters.ascii-manager-ptr": "00b94700",
        "ExpHP.debug-counters.color-data": "<codecave:ExpHP.debug-counters.ascii-manager-ptr>2462000005000000",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000ff7514ff7510ff750cff7508b850164000ffd083c410c9c21000",
        "ExpHP.debug-counters.bullet-data": "05000000183f6d00f85f5a000300000010000000efbeaddef635410000000000045c0f00",
        "ExpHP.debug-counters.normal-item-data": "05000000183f6d0068e269000300000010000000efbeaddefbf241000000000048890200",
        "ExpHP.debug-counters.cancel-item-data": "00000000",
        "ExpHP.debug-counters.laser-data": "05000000183f6d00f85f5a00010000001c000000efbeaddee13441000000000000c00e005802000070020000<codecave:base-exphp.adjust-laser-array>",
        "ExpHP.debug-counters.enemy-data": "05000000183f6d00c8794b000300000010000000efbeadde00000000ffffff7fbce50e00",
        "ExpHP.debug-counters.effect-general-data": "05000000183f6d00e07f4800010000001c000000efbeadde32f140000000000008000000780100007c01000000000000",
        "ExpHP.debug-counters.effect-familiar-data": "00000000",
        "ExpHP.debug-counters.effect-indexed-data": "00000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.effect-indexed-data>253764206566662e49000000<codecave:ExpHP.debug-counters.effect-general-data>253764206566662e47000000<codecave:ExpHP.debug-counters.bullet-data>253764206574616d61000000<codecave:ExpHP.debug-counters.laser-data>253764206c61736572000000<codecave:ExpHP.debug-counters.normal-item-data>253764206974656d20000000<codecave:ExpHP.debug-counters.enemy-data>25376420656e656d7900000000000000",
        "of(ExpHP.debug-counters.draw)": "e8[codecave:ExpHP.debug-counters.show-debug-data]b900b94700e800000000c70424e9404200c3"
    }
}
