{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x4240e4",
            "expected": "b900b94700",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    },
    "codecaves": {
        "ExpHP.debug-counters.ascii-manager-ptr": "00b94700",
        "ExpHP.debug-counters.color-data": "<codecave:ExpHP.debug-counters.ascii-manager-ptr>24620000",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000ff7514ff7510ff750cff7508b850164000ffd083c410c9c21000",
        "ExpHP.debug-counters.bullet-data": "05000000183f6d00f85f5a000300000014000000efbeaddef635410000000000045c0f0000010000",
        "ExpHP.debug-counters.normal-item-data": "05000000183f6d0068e269000300000014000000efbeaddefbf24100000000004889020001010000",
        "ExpHP.debug-counters.cancel-item-data": "00000000",
        "ExpHP.debug-counters.laser-data": "05000000183f6d00f85f5a00010000001c000000efbeaddee13441000000000000c00e00580200007002000000010000",
        "ExpHP.debug-counters.enemy-data": "05000000183f6d00c8794b000300000014000000efbeadde2d24410000000000bce50e0000000000",
        "ExpHP.debug-counters.effect-general-data": "05000000183f6d00e07f4800010000001c000000efbeadde83ef40000000000008000000780100007c01000000000000",
        "ExpHP.debug-counters.effect-familiar-data": "00000000",
        "ExpHP.debug-counters.effect-indexed-data": "00000000",
        "ExpHP.debug-counters.line-info": "020500000000dd430000e84300000000000060c103050000<codecave:ExpHP.debug-counters.effect-indexed-data>253764206566662e4900000003050000<codecave:ExpHP.debug-counters.effect-general-data>253764206566662e4700000003050000<codecave:ExpHP.debug-counters.bullet-data>253764206574616d6100000003050000<codecave:ExpHP.debug-counters.laser-data>253764206c6173657200000003050000<codecave:ExpHP.debug-counters.normal-item-data>253764206974656d2000000003050000<codecave:ExpHP.debug-counters.enemy-data>25376420656e656d7900000001050000",
        "of(ExpHP.debug-counters.draw)": "e8[codecave:ExpHP.debug-counters.show-debug-data]b900b94700e800000000c70424e9404200c3"
    }
}
