{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "<codecave:ExpHP.debug-counters.ascii-manager-ptr> // C0740000 // 04000000",
        "ExpHP.debug-counters.ascii-manager-ptr": "18CE3401",
        "ExpHP.debug-counters.drawf-debug-int": "5589E55657 // 53 // FF7514 // FF7510 // FF750C // FF7508 // B860204000 // FFD0 // 83C410 // 5B // 5F5E89EC5D // C21000",
        "ExpHP.debug-counters.bullet-data": "05000000 // 489E4B00 // 58F96200 // 03000000 // 10000000 // EFBEADDE // 6C37420000000000 // 28A13700",
        "ExpHP.debug-counters.normal-item-data": "05000000 // 489E4B00 // 705C5700 // 03000000 // 10000000 // EFBEADDE // 4C27430000000000 // ECE20A00",
        "ExpHP.debug-counters.cancel-item-data": "00000000",
        "ExpHP.debug-counters.laser-data": "05000000 // 489E4B00 // 58F96200 // 06000000 // 1C000000 // EFBEADDE // AD33420000000000 // 28663600 // 4D0D0000 // EC040000 // <codecave:base-exphp.adjust-laser-array>",
        "ExpHP.debug-counters.enemy-data": "05000000 // 489E4B00 // 009B9A00 // 03000000 // 10000000 // EFBEADDE // 00000000FFFFFF7F // BC459500",
        "ExpHP.debug-counters.effect-general-data": "05000000 // 489E4B00 // 50E22F01 // 01000000 // 18000000 // EFBEADDE // F3C1410000000000 // 1C000000 // CC020000 // D8020000",
        "ExpHP.debug-counters.effect-indexed-data": "05000000 // 489E4B00 // 50E22F01 // 01000000 // 18000000 // EFBEADDE // 000000000D000000 // 9C710400 // CC020000 // D8020000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.effect-indexed-data> // 253764206566662E49000000 // <codecave:ExpHP.debug-counters.effect-general-data> // 253764206566662E47000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D73000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // A148F66200 // E800000000C7042496934300C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x439391",
            "expected": "a148f66200",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    }
}
