{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "<codecave:ExpHP.debug-counters.ascii-manager-ptr> // 68820000 // 04000000",
        "ExpHP.debug-counters.ascii-manager-ptr": "20CE4C00",
        "ExpHP.debug-counters.drawf-debug-int": "55 89E5 56 57 // 53 // FF7514 // FF7510 // FF750C // FF7508 // B8302A4000 // FFD0 // 83C410 // 5B // 5F 5E 89EC 5D // C21000",
        "ExpHP.debug-counters.bullet-data": "05000000 // 288A8B01 // 904EF500 // 03000000 // 0C000000 // EFBEADDE // 38A56B00 // AA124300",
        "ExpHP.debug-counters.normal-item-data": "05000000 // 288A8B01 // 48366501 // 03000000 // 0C000000 // EFBEADDE // A8AD1700 // 83014400",
        "ExpHP.debug-counters.cancel-item-data": "00000000",
        "ExpHP.debug-counters.laser-data": "05000000 // 288A8B01 // 904EF500 // 06000000 // 20000000 // EFBEADDE // 01000000 // 00000000 // 60F44200 // 38096600 // 84050000 // 9C050000 // 04000000",
        "ExpHP.debug-counters.effect-1-data": "05000000 // 288A8B01 // 60CE4E00 // 01000000 // 1C000000 // EFBEADDE // 01000000 // 00000000 // 64544200 // 1C000000 // 50030000 // 60030000",
        "ExpHP.debug-counters.effect-2-data": "05000000 // 288A8B01 // 60CE4E00 // 01000000 // 1C000000 // EFBEADDE // 01000000 // 00000000 // A55B4200 // 1CC00600 // 50030000 // 60030000",
        "ExpHP.debug-counters.effect-3-data": "05000000 // 288A8B01 // 60CE4E00 // 01000000 // 1C000000 // EFBEADDE // 00000000 // 00000000 // 0D000000 // 1C700800 // 50030000 // 60030000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.effect-3-data> // 253764206566662E33000000 // <codecave:ExpHP.debug-counters.effect-2-data> // 253764206566662E32000000 // <codecave:ExpHP.debug-counters.effect-1-data> // 253764206566662E31000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D73000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // A1B4D06401 // E800000000C70424 2a724400 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x447225",
            "expected": "a1b4d06401",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    }
}
