{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.ascii-manager-ptr": "20ce4c00",
        "ExpHP.debug-counters.color-data": "<codecave:ExpHP.debug-counters.ascii-manager-ptr>6882000004000000",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000ff7514ff7510ff750cff7508b8302a4000ffd083c410c9c21000",
        "ExpHP.debug-counters.bullet-data": "05000000288a8b01904ef5000300000010000000efbeaddeaa1243000000000038a56b00",
        "ExpHP.debug-counters.normal-item-data": "05000000288a8b01483665010300000010000000efbeadde8301440000000000a8ad1700",
        "ExpHP.debug-counters.cancel-item-data": "00000000",
        "ExpHP.debug-counters.laser-data": "05000000288a8b01904ef500010000001c000000efbeadde60f442000000000038096600840500009c050000<codecave:base-exphp.adjust-laser-array>",
        "ExpHP.debug-counters.enemy-data": "05000000288a8b01207f57000300000010000000efbeadde00000000ffffff7fc4cd9d00",
        "ExpHP.debug-counters.effect-general-data": "05000000288a8b0160ce4e00010000001c000000efbeadde64544200000000001c000000500300006003000000000000",
        "ExpHP.debug-counters.effect-familiar-data": "05000000288a8b0160ce4e00010000001c000000efbeaddea55b4200000000001cc00600500300006003000000000000",
        "ExpHP.debug-counters.effect-indexed-data": "05000000288a8b0160ce4e00010000001c000000efbeadde000000000d0000001c700800500300006003000000000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.effect-indexed-data> // 253764206566662E49000000 // <codecave:ExpHP.debug-counters.effect-general-data> // 253764206566662E47000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D73000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // A1B4D06401 // E800000000C70424 2a724400 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x447225",
            "expected": "a1b4d06401",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    }
}
