{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x431918",
            "expected": "b958e44c00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    },
    "codecaves": {
        "ExpHP.debug-counters.ascii-manager-ptr": "58e44c00",
        "ExpHP.debug-counters.color-data": "<codecave:ExpHP.debug-counters.ascii-manager-ptr>68820000",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000ff7514ff7510ff750cff7508b830434300ffd083c410c9c21000",
        "ExpHP.debug-counters.p1-bullet-fairy-data": "03000000987d4a006b504100ffffffff64e1250000010000",
        "ExpHP.debug-counters.p1-bullet-rival-data": "03000000987d4a0086504100ffffffff68e1250000010000",
        "ExpHP.debug-counters.p1-laser-data": "01000000987d4a00113c4100ffffffff24d42400840500009c05000000010000",
        "ExpHP.debug-counters.p1-enemy-data": "03000000a07d4a003516410000000000acc32a0000000000",
        "ExpHP.debug-counters.p1-enemy-fairy-data": "03000000a07d4a003516410000000000b0c32a0000000000",
        "ExpHP.debug-counters.p1-enemy-boss-data": "03000000a07d4a003516410000000000b4c32a0000000000",
        "ExpHP.debug-counters.p1-enemy-charge-data": "03000000a07d4a003516410000000000b8c32a0000000000",
        "ExpHP.debug-counters.p2-bullet-fairy-data": "03000000d07d4a006b504100ffffffff64e1250000010000",
        "ExpHP.debug-counters.p2-bullet-rival-data": "03000000d07d4a0086504100ffffffff68e1250000010000",
        "ExpHP.debug-counters.p2-laser-data": "01000000d07d4a00113c4100ffffffff24d42400840500009c05000000010000",
        "ExpHP.debug-counters.p2-enemy-data": "03000000d87d4a003516410000000000acc32a0000000000",
        "ExpHP.debug-counters.p2-enemy-fairy-data": "03000000d87d4a003516410000000000b0c32a0000000000",
        "ExpHP.debug-counters.p2-enemy-boss-data": "03000000d87d4a003516410000000000b4c32a0000000000",
        "ExpHP.debug-counters.p2-enemy-charge-data": "03000000d87d4a003516410000000000b8c32a0000000000",
        "ExpHP.debug-counters.line-info": "02050000000036430000164300000000000020c103050000<codecave:ExpHP.debug-counters.p1-bullet-fairy-data>2537642065742e596f00000003050000<codecave:ExpHP.debug-counters.p1-bullet-rival-data>2537642065742e503200000003050000<codecave:ExpHP.debug-counters.p1-laser-data>253764206c6173657200000003050000<codecave:ExpHP.debug-counters.p1-enemy-data>25376420656e656d79000000020500000000fb430000164300000000000020c103050000<codecave:ExpHP.debug-counters.p2-bullet-fairy-data>2537642065742e596f00000003050000<codecave:ExpHP.debug-counters.p2-bullet-rival-data>2537642065742e503100000003050000<codecave:ExpHP.debug-counters.p2-laser-data>253764206c6173657200000003050000<codecave:ExpHP.debug-counters.p2-enemy-data>25376420656e656d7900000001050000",
        "of(ExpHP.debug-counters.draw)": "e8[codecave:ExpHP.debug-counters.show-debug-data]b958e44c00e800000000c704241d194300c3"
    }
}
