{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "e07647007489000001000000",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000535657ff7514ff75108b5d0c8b7508b890164000ffd083c4085f5e5bc9c21000",
        "ExpHP.debug-counters.bullet-data": "01000000f076470052584200000000006000000046040000f007000000000000",
        "ExpHP.debug-counters.normal-item-data": "0100000018784700000000009600000014000000dc030000f003000000000000",
        "ExpHP.debug-counters.cancel-item-data": "010000001878470012af41006affffffb44e0200dc030000f003000000000000",
        "ExpHP.debug-counters.laser-data": "030000001c78470016c541000000000038040000",
        "ExpHP.debug-counters.anmid-data": "02000000101c49000000000000100000d4da7200dcda7200",
        "ExpHP.debug-counters.enemy-data": "070000000477470000000000ffffff7f58000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // A1E0764700 // E800000000C70424 58364100 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x413653",
            "expected": "a1e0764700",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    }
}
