{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "588D4A00 // 80840100 // 02000000",
        "ExpHP.debug-counters.drawf-debug-int": "5589E55657 // 53 // FF7514 // FF7510 // 8B5D0C // 8B4D08 // B800164000 // FFD0 // 83C408 // 5B // 5F5E89EC5D // C21000",
        "ExpHP.debug-counters.bullet-data": "01000000 // 688D4A00 // 3C8D400000000000 // 64000000 // B2040000 // 10090000",
        "ExpHP.debug-counters.normal-item-data": "01000000 // 908E4A00 // 0000000096000000 // 14000000 // 64040000 // 78040000",
        "ExpHP.debug-counters.cancel-item-data": "01000000 // 908E4A00 // 8C3442006AFFFFFF // 649E0200 // 64040000 // 78040000",
        "ExpHP.debug-counters.laser-data": "03000000 // 948E4A00 // FD4D420000000000 // 54040000",
        "ExpHP.debug-counters.anmid-data": "02000000 // 68324C00 // 0000000000100000 // 2C567B00 // 34567B00",
        "ExpHP.debug-counters.enemy-data": "03000000 // 7C8D4A00 // 00000000FFFFFF7F // 70000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // 8B0D588D4A00 // E800000000C70424 319f4100 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x419f2b",
            "expected": "8b0d588d4a00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)] // CC"
        }
    }
}
