{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "588d4a008084010002000000",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000535657ff7514ff75108b5d0c8b4d08b800164000ffd083c4085f5e5bc9c21000",
        "ExpHP.debug-counters.bullet-data": "01000000688d4a003c8d40000000000064000000b204000010090000",
        "ExpHP.debug-counters.normal-item-data": "01000000908e4a000000000096000000140000006404000078040000",
        "ExpHP.debug-counters.cancel-item-data": "01000000908e4a008c3442006affffff649e02006404000078040000",
        "ExpHP.debug-counters.laser-data": "03000000948e4a00fd4d42000000000054040000",
        "ExpHP.debug-counters.anmid-data": "0200000068324c0000000000001000002c567b0034567b00",
        "ExpHP.debug-counters.enemy-data": "030000007c8d4a0000000000ffffff7f70000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // 8B0D588D4A00 // E800000000C70424 319f4100 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x419f2b",
            "expected": "8b0d588d4a00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)] // CC"
        }
    }
}
