{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "20894B00 // 4CC80100",
        "ExpHP.debug-counters.drawf-debug-int": "55 89E5 56 57 // 83EC04 // 89E7 // FF7514 // FF7510 // FF750C // 8B7508 // B800194000 // FFD0 // 83C40C // 83C404 // 5F 5E 89EC 5D // C21000",
        "ExpHP.debug-counters.bullet-data": "01000000 // 30894B00 // 01000000 // 00000000 // 918D4000 // 64000000 // 2A0A0000 // B8110000",
        "ExpHP.debug-counters.normal-item-data": "01000000 // 5C8A4B00 // 00000000 // 00000000 // 58020000 // 14000000 // 180A0000 // 400A0000",
        "ExpHP.debug-counters.cancel-item-data": "01000000 // 5C8A4B00 // 01000000 // 98FDFFFF // 4C854200 // 14AA1800 // 180A0000 // 400A0000",
        "ExpHP.debug-counters.laser-data": "03000000 // 608A4B00 // D4050000 // 0DA44200",
        "ExpHP.debug-counters.anmid-data": "02000000 // 502E4D00 // 04978B00 // 08978B00 // 00100000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // 8B1520894B00 // E800000000C70424 36fb4100 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x41fb30",
            "expected": "8b1520894b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)] // CC"
        }
    }
}
