{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "B8434B00 // 808F0100 // 02000000",
        "ExpHP.debug-counters.drawf-debug-int": "5589E55657 // 53 // FF7514 // FF7510 // 8B5D0C // 8B7508 // B820174000 // FFD0 // 83C408 // 5B // 5F5E89EC5D // C21000",
        "ExpHP.debug-counters.bullet-data": "01000000 // C8434B00 // 61A0400000000000 // 64000000 // 32050000 // F8090000",
        "ExpHP.debug-counters.normal-item-data": "01000000 // F0444B00 // 0000000058020000 // 14000000 // B0090000 // D8090000",
        "ExpHP.debug-counters.cancel-item-data": "01000000 // F0444B00 // 5C5B420098FDFFFF // D4AF1700 // B0090000 // D8090000",
        "ExpHP.debug-counters.laser-data": "03000000 // F4444B00 // 5D84420000000000 // 68040000",
        "ExpHP.debug-counters.anmid-data": "02000000 // CCE84C00 // 0000000000100000 // B8568800 // C0568800",
        "ExpHP.debug-counters.enemy-data": "03000000 // DC434B00 // 00000000FFFFFF7F // 70000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // 8B0DB8434B00 // E800000000C70424 26cd4100 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x41cd20",
            "expected": "8b0db8434b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)] // CC"
        }
    }
}
