{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.drawf-debug-int": "55 89E5 56 57 // FF750C // FF7514 // E8[codecave:ExpHP.debug-counters.get-color] // 8B0DB8434B00 // 8981808F0100 // 8B35B8434B00 // 8B5D08 // FF7514 // FF7510 // B820174000 // FFD0 // 83C408 // 8B0DB8434B00 // C781808F0100FFFFFFFF // 5F 5E 89EC 5D // C21000",
        "ExpHP.debug-counters.bullet-data": "01000000 // C8434B00 // 01000000 // 00000000 // 61A04000 // 64000000 // 32050000 // F8090000",
        "ExpHP.debug-counters.normal-item-data": "01000000 // F0444B00 // 00000000 // 00000000 // 58020000 // 14000000 // B0090000 // D8090000",
        "ExpHP.debug-counters.cancel-item-data": "01000000 // F0444B00 // 01000000 // 98FDFFFF // 5C5B4200 // D4AF1700 // B0090000 // D8090000",
        "ExpHP.debug-counters.laser-data": "03000000 // F4444B00 // 68040000 // 5D844200",
        "ExpHP.debug-counters.anmid-data": "02000000 // CCE84C00 // B8568800 // C0568800 // 00100000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // 8B0DB8434B00 // E800000000 // C7042426CD4100 // C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x41cd20",
            "expected": "8b0db8434b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)] // CC"
        }
    }
}
