{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "70674B00 // F4C70100 // 02000000",
        "ExpHP.debug-counters.drawf-debug-int": "55 89E5 56 57 // 83EC04 // 89E7 // FF7514 // FF7510 // FF750C // 8B7508 // B830184000 // FFD0 // 83C40C // 83C404 // 5F 5E 89EC 5D // C21000",
        "ExpHP.debug-counters.bullet-data": "01000000 // 7C674B00 // 01000000 // 00000000 // 81874000 // 64000000 // 12050000 // 340A0000",
        "ExpHP.debug-counters.normal-item-data": "04000000 // A0684B00",
        "ExpHP.debug-counters.cancel-item-data": "01000000 // A0684B00 // 01000000 // 00000000 // 1CF34100 // 14000000 // F0040000 // F4040000",
        "ExpHP.debug-counters.laser-data": "03000000 // A4684B00 // 68040000 // 0D044200",
        "ExpHP.debug-counters.anmid-data": "02000000 // B40C4D00 // C0D68800 // C8D68800 // 00100000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // 8B1570674B00 // E800000000C70424 2baf4100 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x41af25",
            "expected": "8b1570674b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)] // CC"
        }
    }
}
