{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x41fb30",
            "expected": "8b1520894b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)] // CC"
        }
    },
    "codecaves": {
        "ExpHP.debug-counters.color-data": "20894b004cc80100",
        "ExpHP.debug-counters.drawf-debug-int": "c800000053565783ec0489e7ff7514ff7510ff750c8b7508b800194000ffd083c40c83c4045f5e5bc9c21000",
        "ExpHP.debug-counters.bullet-data": "0100000030894b00918d400000000000640000002a0a0000b811000000000000",
        "ExpHP.debug-counters.normal-item-data": "010000005c8a4b00000000005802000014000000180a0000400a000000000000",
        "ExpHP.debug-counters.cancel-item-data": "010000005c8a4b004c85420098fdffff14aa1800180a0000400a000000000000",
        "ExpHP.debug-counters.laser-data": "03000000608a4b000da4420000000000d4050000",
        "ExpHP.debug-counters.anmid-data": "02000000502e4d00000000000010000004978b0008978b00",
        "ExpHP.debug-counters.enemy-data": "0300000048894b0000000000ffffff7fc0000000",
        "ExpHP.debug-counters.line-info": "02050000008008440000e64300000000000020c103050000<codecave:ExpHP.debug-counters.anmid-data>25376420616e6d696400000003050000<codecave:ExpHP.debug-counters.bullet-data>253764206574616d6100000003050000<codecave:ExpHP.debug-counters.laser-data>253764206c6173657200000003050000<codecave:ExpHP.debug-counters.normal-item-data>253764206974656d4e00000003050000<codecave:ExpHP.debug-counters.cancel-item-data>253764206974656d4300000003050000<codecave:ExpHP.debug-counters.enemy-data>25376420656e656d7900000001050000",
        "of(ExpHP.debug-counters.draw)": "e8[codecave:ExpHP.debug-counters.show-debug-data]8b1520894b00e800000000c7042436fb4100c3"
    }
}
