{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "60214c006091010002000000",
        "ExpHP.debug-counters.drawf-debug-int": "c800000053565783ec0489e7ff7514ff75108b5d0c8b7508b8e0404000ffd083c40883c4045f5e5bc9c21000",
        "ExpHP.debug-counters.bullet-data": "0100000074214c006cd94000ffffffff90000000be0b00005c13000000000000",
        "ExpHP.debug-counters.normal-item-data": "010000009c224c00000000005802000014000000a00b0000c80b000000000000",
        "ExpHP.debug-counters.cancel-item-data": "010000009c224c00bce24200a8fdffffd49c1b00a00b0000c80b000000000000",
        "ExpHP.debug-counters.laser-data": "03000000a0224c00ddfe420000000000d4050000",
        "ExpHP.debug-counters.anmid-data": "0200000088c64d0000000000ff1f00000882f4001082f400",
        "ExpHP.debug-counters.spirit-data": "03000000a4224c00748643000000000014880000",
        "ExpHP.debug-counters.enemy-data": "0300000088214c0000000000ffffff7fb8000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.spirit-data> // 253764206C676F6473000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // 8B0D60214C00 // E800000000C70424 324b4200 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x424b2c",
            "expected": "8b0d60214c00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)] // CC"
        }
    }
}
