{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "20b54d00b091010003000000",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000ff7514ff7510ff750cff7508b8c0bd4000ffd083c410c9c21000",
        "ExpHP.debug-counters.bullet-data": "0100000030b54d005c654100ffffffff8c0000000e0c0000f413000000000000",
        "ExpHP.debug-counters.normal-item-data": "0100000060b64d00000000005802000014000000f00b0000180c000000000000",
        "ExpHP.debug-counters.cancel-item-data": "0100000060b64d007d844300a8fdffff54581c00f00b0000180c000000000000",
        "ExpHP.debug-counters.laser-data": "0300000064b64d0061a7430000000000d4050000",
        "ExpHP.debug-counters.anmid-data": "02000000cc564f0000000000ff1f00000882fe001082fe00",
        "ExpHP.debug-counters.enemy-data": "0300000044b54d0000000000ffffff7fd8000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // A120B54D00 // E800000000C70424 58e64200 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x42e653",
            "expected": "a120b54d00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    }
}
