{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "589A4E00 // 24920100 // 03000000",
        "ExpHP.debug-counters.drawf-debug-int": "5589E55657 // FF7514 // FF7510 // FF750C // FF7508 // B800C84000 // FFD0 // 83C410 // 5F5E89EC5D // C21000",
        "ExpHP.debug-counters.bullet-data": "01000000 // 6C9A4E00 // 958C4100FFFFFFFF // 98000000 // 8A0C0000 // 94140000",
        "ExpHP.debug-counters.normal-item-data": "01000000 // 9C9A4E00 // 0000000058020000 // 10000000 // 640C0000 // 880C0000",
        "ExpHP.debug-counters.cancel-item-data": "01000000 // 9C9A4E00 // 54F44300A8FDFFFF // D05E1D00 // 640C0000 // 880C0000",
        "ExpHP.debug-counters.laser-data": "03000000 // A09B4E00 // E119440000000000 // E4050000",
        "ExpHP.debug-counters.anmid-data": "02000000 // 183C5000 // 00000000FF1F0000 // DC000000 // E4000000",
        "ExpHP.debug-counters.enemy-data": "03000000 // 809A4E00 // 00000000FFFFFF7F // 8C010000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // A1589A4E00 // E800000000C70424 78374300 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x433773",
            "expected": "a1589a4e00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    }
}
