{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "F8544B00 // 0CC90100 // 03000000",
        "ExpHP.debug-counters.drawf-debug-int": "5589E55657 // 83EC04 // 89E1 // FF7514 // FF7510 // FF750C // 51 // FF7508 // B810834000 // FFD0 // 83C414 // 83C404 // 5F5E89EC5D // C21000",
        "ExpHP.debug-counters.bullet-data": "01000000 // 0C554B00 // C3EB4000FFFFFFFF // 9C000000 // 540E0000 // 8C0E0000",
        "ExpHP.debug-counters.normal-item-data": "04000000 // 34564B00",
        "ExpHP.debug-counters.cancel-item-data": "01000000 // 34564B00 // 42BB420000000000 // 10000000 // 30060000 // 34060000",
        "ExpHP.debug-counters.laser-data": "03000000 // 38564B00 // 61CB420000000000 // E4050000",
        "ExpHP.debug-counters.anmid-data": "02000000 // 8CD84E00 // 00000000FF1F0000 // DC000000 // E4000000",
        "ExpHP.debug-counters.enemy-data": "03000000 // 1C554B00 // 00000000FFFFFF7F // B4010000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // A1F8544B00 // E800000000C70424 6c424200 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x424267",
            "expected": "a1f8544b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    }
}
