{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x424267",
            "expected": "a1f8544b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    },
    "codecaves": {
        "ExpHP.debug-counters.color-data": "f8544b000cc90100",
        "ExpHP.debug-counters.drawf-debug-int": "c800000083ec0489e1ff7514ff7510ff750c51ff7508b810834000ffd083c41483c404c9c21000",
        "ExpHP.debug-counters.bullet-data": "010000000c554b00c3eb4000ffffffff9c000000540e00008c0e000000000000",
        "ExpHP.debug-counters.normal-item-data": "0400000034564b00",
        "ExpHP.debug-counters.cancel-item-data": "0100000034564b0042bb42000000000010000000300600003406000000000000",
        "ExpHP.debug-counters.laser-data": "0300000038564b0061cb420000000000e4050000",
        "ExpHP.debug-counters.anmid-data": "020000008cd84e0000000000ff1f0000dc000000e4000000",
        "ExpHP.debug-counters.enemy-data": "030000001c554b0000000000ffffff7fb4010000",
        "ExpHP.debug-counters.effect-data": "0100000018554b00ed5e4100000000001c000000bdffffff0400000000000000",
        "ExpHP.debug-counters.line-info": "0205000000000a440000e64300000000000020c103050000<codecave:ExpHP.debug-counters.anmid-data>25376420616e6d696400000003050000<codecave:ExpHP.debug-counters.effect-data>25376420656666202000000003050000<codecave:ExpHP.debug-counters.bullet-data>253764206574616d6100000003050000<codecave:ExpHP.debug-counters.laser-data>253764206c6173657200000003050000<codecave:ExpHP.debug-counters.normal-item-data>253764206974656d4e00000003050000<codecave:ExpHP.debug-counters.cancel-item-data>253764206974656d4300000003050000<codecave:ExpHP.debug-counters.enemy-data>25376420656e656d7900000001050000",
        "of(ExpHP.debug-counters.draw)": "e8[codecave:ExpHP.debug-counters.show-debug-data]a1f8544b00e800000000c704246c424200c3"
    }
}
