{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x429fc3",
            "expected": "a178764b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    },
    "codecaves": {
        "ExpHP.debug-counters.color-data": "78764b0014920100",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000ff7514ff7510ff750cff7508b830854000ffd083c410c9c21000",
        "ExpHP.debug-counters.bullet-data": "010000008c764b0003484100ffffffffec000000500e0000880e000000000000",
        "ExpHP.debug-counters.normal-item-data": "01000000b8764b00000000005802000014000000580c0000780c000000000000",
        "ExpHP.debug-counters.cancel-item-data": "01000000b8764b00f4314300a8fdffff54391d00580c0000780c000000000000",
        "ExpHP.debug-counters.laser-data": "03000000bc764b00d155430000000000e4050000",
        "ExpHP.debug-counters.anmid-data": "02000000209a500000000000ff3f0000dc060000e4060000",
        "ExpHP.debug-counters.enemy-data": "03000000a0764b0000000000ffffff7f8c010000",
        "ExpHP.debug-counters.effect-data": "0100000098764b00ddb74100000000001c000000bdffffff0400000000000000",
        "ExpHP.debug-counters.line-info": "0205000000000a440000e64300000000000020c103050000<codecave:ExpHP.debug-counters.anmid-data>25376420616e6d696400000003050000<codecave:ExpHP.debug-counters.effect-data>25376420656666202000000003050000<codecave:ExpHP.debug-counters.bullet-data>253764206574616d6100000003050000<codecave:ExpHP.debug-counters.laser-data>253764206c6173657200000003050000<codecave:ExpHP.debug-counters.normal-item-data>253764206974656d4e00000003050000<codecave:ExpHP.debug-counters.cancel-item-data>253764206974656d4300000003050000<codecave:ExpHP.debug-counters.enemy-data>25376420656e656d7900000001050000",
        "of(ExpHP.debug-counters.draw)": "e8[codecave:ExpHP.debug-counters.show-debug-data]a178764b00e800000000c70424c89f4200c3"
    }
}
