{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "ExpHP.debug-counters.color-data": "78764B00 // 14920100 // 03000000",
        "ExpHP.debug-counters.drawf-debug-int": "5589E55657 // FF7514 // FF7510 // FF750C // FF7508 // B830854000 // FFD0 // 83C410 // 5F5E89EC5D // C21000",
        "ExpHP.debug-counters.bullet-data": "01000000 // 8C764B00 // 03484100FFFFFFFF // EC000000 // 500E0000 // 880E0000",
        "ExpHP.debug-counters.normal-item-data": "01000000 // B8764B00 // 0000000058020000 // 14000000 // 580C0000 // 780C0000",
        "ExpHP.debug-counters.cancel-item-data": "01000000 // B8764B00 // F4314300A8FDFFFF // 54391D00 // 580C0000 // 780C0000",
        "ExpHP.debug-counters.laser-data": "03000000 // BC764B00 // D155430000000000 // E4050000",
        "ExpHP.debug-counters.anmid-data": "02000000 // 209A5000 // 00000000FF3F0000 // DC060000 // E4060000",
        "ExpHP.debug-counters.enemy-data": "03000000 // A0764B00 // 00000000FFFFFF7F // 8C010000",
        "ExpHP.debug-counters.effect-data": "01000000 // 98764B00 // DDB7410000000000 // 1C000000 // BDFFFFFF // 04000000",
        "ExpHP.debug-counters.line-info": "<codecave:ExpHP.debug-counters.anmid-data> // 25376420616E6D6964000000 // <codecave:ExpHP.debug-counters.effect-data> // 253764206566662020000000 // <codecave:ExpHP.debug-counters.bullet-data> // 253764206574616D61000000 // <codecave:ExpHP.debug-counters.laser-data> // 253764206C61736572000000 // <codecave:ExpHP.debug-counters.normal-item-data> // 253764206974656D4E000000 // <codecave:ExpHP.debug-counters.cancel-item-data> // 253764206974656D43000000 // <codecave:ExpHP.debug-counters.enemy-data> // 25376420656E656D79000000 // 00000000",
        "of(ExpHP.debug-counters.draw)": "E8[codecave:ExpHP.debug-counters.show-debug-data] // A178764B00 // E800000000C70424 c89f4200 C3"
    },
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x429fc3",
            "expected": "a178764b00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    }
}
