{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.debug-counters.draw": {
            "addr": "0x43a3d3",
            "expected": "a1acf24c00",
            "code": "E9 [codecave:of(ExpHP.debug-counters.draw)]"
        }
    },
    "codecaves": {
        "ExpHP.debug-counters.color-data": "acf24c0028920100",
        "ExpHP.debug-counters.drawf-debug-int": "c8000000ff7514ff7510ff750cff7508b810a14100ffd083c410c9c21000",
        "ExpHP.debug-counters.bullet-data": "01000000bcf24c00333b4200ffffffffec000000680f0000a00f000000010000",
        "ExpHP.debug-counters.normal-item-data": "01000000ecf24c00000000005802000014000000740c0000940c000001010000",
        "ExpHP.debug-counters.cancel-item-data": "01000000ecf24c0064584400a8fdfffff47a1d00740c0000940c000001010000",
        "ExpHP.debug-counters.laser-data": "03000000f4f34c0031894400000000009807000000000000",
        "ExpHP.debug-counters.anmid-data": "020000005cf6510000000000ff7f0000f0060000f8060000",
        "ExpHP.debug-counters.enemy-data": "03000000d0f24c0000000000ffffff7f9801000000000000",
        "ExpHP.debug-counters.effect-data": "01000000c8f24c003daf4200000000001c000000bdffffff0400000000000000",
        "ExpHP.debug-counters.line-info": "0205000000000a440000e64300000000000020c103050000<codecave:ExpHP.debug-counters.anmid-data>25376420616e6d696400000003050000<codecave:ExpHP.debug-counters.effect-data>25376420656666202000000003050000<codecave:ExpHP.debug-counters.bullet-data>253764206574616d6100000003050000<codecave:ExpHP.debug-counters.laser-data>253764206c6173657200000003050000<codecave:ExpHP.debug-counters.normal-item-data>253764206974656d4e00000003050000<codecave:ExpHP.debug-counters.cancel-item-data>253764206974656d4300000003050000<codecave:ExpHP.debug-counters.enemy-data>25376420656e656d7900000001050000",
        "of(ExpHP.debug-counters.draw)": "e8[codecave:ExpHP.debug-counters.show-debug-data]a1acf24c00e800000000c70424d8a34300c3"
    }
}
