#!/usr/bin/env bash

"$(dirname "$0")/list-asm-minimal" "$@" |
    # These make *almost* everything into yaml
    sed -E 's@^( *[0-9]+ +[^ ;].+FIXUP)@!!\1@' |   # prevent lines with the word FIXUP from matching other
                                                   # regexes so that they stand out in the generated output.
                                                   # (these are lines that need manual fixes)
                                                   #
                                                   # The " *[0-9]+ +[^ ;]" checks that the entire line isn't commented out.
    sed -E 's@ <[0-9]+>@@' |    # kill <1>, <2>... in expanded macros
    sed -E 's@^( *[0-9]+ [0-9A-F]{8} [0-9A-Z\[]{18})-@\1@' |    # kill continuation dashes
    sed -E 's@^ *[0-9]+ [0-9A-F]{8} ([0-9A-Z\[].{17}) *@    - "\1" # @' |    # format as sequence items
    sed -E 's@^ *[0-9]+ +;@    #@' |    # Turn whole-line ; comments to # comments
    sed -E 's@^ *[0-9]+ *$@@' |    # strip line numbers from empty lines
    sed -E 's@^ *[0-9]+     +@    # @' |   # turn lines without hex code into comments

    # Alright, everything else is too hard to sed.
    python3 scripts/list-asm-postprocess.py

rm -f "$TEMPFILE"
