#!/usr/bin/env bash

"$(dirname "$0")/list-asm-minimal" "$@" |
    # kill <1>, <2>... in expanded macros and included files
    sed -E 's@ <[0-9]+>@@' |

    # Strip struct definitions
    sed -E '/^ *[0-9]+ +struc /,/^ *[0-9]+ +endstruc/ { d }' |
    # Strip istruc, iend
    egrep -v '/^ *[0-9]+ (istruc|iend)\b/' |

    # These make *almost* everything into yaml
    sed -E 's@^( *[0-9]+ [0-9A-F]{8} [0-9A-Z\[]{18})-@\1@' |    # kill continuation dashes
    sed -E 's@^ *[0-9]+ [0-9A-F]{8} ([0-9A-Z\[].{17}) *@    - "\1" # @' |    # format as sequence items
    sed -E 's@^ *[0-9]+ +;@    #@' |    # Turn whole-line ; comments to # comments
    sed -E 's@^ *[0-9]+ *$@@' |    # strip line numbers from empty lines
    sed -E 's@^ *[0-9]+     +@    # @' |   # turn lines without hex code into comments

    # Alright, everything else is too hard to sed.
    python3 scripts/list-asm-postprocess.py

rm -f "$TEMPFILE"
