{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.auto-release.binhack": {
            "addr": "0x402118",
            "expected": "e863340000",
            "code": "E9 [codecave:of(ExpHP.auto-release.binhack)]"
        }
    },
    "codecaves": {
        "ExpHP.auto-release.autorelease": "E8[codecave:ExpHP.auto-release.is-game-running] // 85C0 // 7435 // E8[codecave:ExpHP.auto-release.is-player-in-danger] // 85C0 // 750B // E8[codecave:ExpHP.auto-release.is-dialogue] // 85C0 // 7519 // EB21 // A1B4504A00 // 25000A0000 // 35000A0000 // 0905B0504A00 // EB0A // 810DB0504A00000A0000 // C3",
        "ExpHP.auto-release.is-game-running": "A1F46E4A00 // 85C0 // 7419 // 8B80EC010000 // 85C0 // 750F // A1F86E4A00 // 85C0 // 7406 // B801000000 // C3 // 31C0 // C3",
        "ExpHP.auto-release.is-dialogue": "A1CC6D4A00 // 85C0 // 7410 // 8B80C8010000 // 85C0 // 7406 // B801000000 // C3 // 31C0 // C3",
        "ExpHP.auto-release.is-player-in-danger": "5589E583EC085657 // 8B0DF86E4A00 // 85C9 // 742A // 8B813C660100 // 83F802 // 7F1F // 8B8110060000 // 8945F8 // 8B8114060000 // 8945FC // FF75FC // FF75F8 // E8[codecave:ExpHP.auto-release.is-bullet-near-pos] // EB02 // 31C0 // 5F5E89EC5D // C3",
        "ExpHP.auto-release.is-bullet-near-pos": "5589E55657 // 8B0DAC6D4A00 // 85C9 // 742E // 8B4970 // 85C9 // 7427 // 8B11 // 6800008041 // FFB2240C0000 // FFB2200C0000 // FF750C // FF7508 // E8[codecave:ExpHP.auto-release.are-points-within] // 85C0 // 7509 // 8B4904 // EBD5 // 31C0 // EB05 // B801000000 // 5F5E89EC5D // C20800",
        "ExpHP.auto-release.are-points-within": "F30F10442404 // F30F5C44240C // F30F104C2408 // F30F5C4C2410 // F30F59C0 // F30F59C9 // F30F58C1 // F30F104C2414 // F30F59C9 // 31C0 // 0F2FC1 // 0F92C0 // C21400",
        "of(ExpHP.auto-release.binhack)": "E8[codecave:ExpHP.auto-release.autorelease] // B9B0504A00 // B880554000 // FFD0 // E800000000C704241D214000C3"
    }
}
