{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "Numguide::disable arrow keys in input": {
            "addr": "0x43b80d",
            "expected": "0fb705b8484d00 // a3d0494d00",
            "code": "E9 [codecave:of(Numguide::disable arrow keys in input)] // CCCCCCCCCCCCCC"
        },
        "Numguide::show numpad guides": {
            "addr": "0x4131e8",
            "expected": "e893180500",
            "code": "E9 [codecave:of(Numguide::show numpad guides)]"
        }
    },
    "codecaves": {
        "ExpHP.numguide.make-all-numguide-anms": "55 89E5 56 57 // 680000C0C2 // E8 [codecave:ExpHP.numguide.make-all-numguide-anms-at-x] // 6A00 // E8 [codecave:ExpHP.numguide.make-all-numguide-anms-at-x] // 680000C042 // E8 [codecave:ExpHP.numguide.make-all-numguide-anms-at-x] // 5F 5E 89EC 5D // C3",
        "ExpHP.numguide.make-all-numguide-anms-at-x": "55 89E5 56 57 // 6800005043 // FF7508 // E8 [codecave:ExpHP.numguide.make-numguide-anm] // 6800009843 // FF7508 // E8 [codecave:ExpHP.numguide.make-numguide-anm] // 680000C843 // FF7508 // E8 [codecave:ExpHP.numguide.make-numguide-anm] // 5F 5E 89EC 5D // C20400",
        "ExpHP.numguide.make-numguide-anm": "55 89E5 56 57 // A1C8434B00 // 8BB0DCEB4D00 // FF8630010000 // B8C0214600 // FFD0 // 89C7 // D94508 // DC05703D4A00 // DC05283D4A00 // D99F30040000 // D9450C // DC05683D4A00 // D99F34040000 // 31C0 // 898738040000 // C7472011000000 // 6A2D // 57 // 89F1 // B8104D4500 // FFD0 // 83EC04 // 8D0424 // 89FB // BF50124600 // FFD7 // 5F 5E 89EC 5D // C20800",
        "of(Numguide::disable arrow keys in input)": "0fb705b8484d00 // 25 0fffffff // a3d0494d00 // F7 05 E8EA4C00 00020000 // b9 19b84300 // ff e1",
        "of(Numguide::show numpad guides)": "837E0408 // 7505 // E8 [codecave:ExpHP.numguide.make-all-numguide-anms] // B8804A4600 // FFD0 // E800000000 // C70424ED314100 // C3"
    }
}
