{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "Spell practice with Bombs and Lives": {
            "addr": "0x42BBDA",
            "expected": "89 3D F4E74B00 // 89 3D 00E84B00",
            "code": "E9 [codecave:of(Spell practice with Bombs and Lives)] // CCCCCCCCCCCCCC"
        }
    },
    "codecaves": {
        "of(Spell practice with Bombs and Lives)": "C7 05 F4E74B00 05000000 // C7 05 00E84B00 05000000 // E800000000 // C70424E6BB4200 // C3"
    }
}
