{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ctrl_speedup::Make ctrl speedup work outside of replays": {
            "code": "66 90",
            "addr": "0x42a3f7",
            "expected": "7524"
        }
    },
    "codecaves": {}
}