{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ctrl_speedup::Make ctrl speedup work outside of replays": {
            "code": "66 90",
            "addr": "0x448e63",
            "expected": "7529"
        },
        "ctrl_speedup::Don't speed up on C key": {
            "code": "66 90",
            "addr": [
                "0x471717",
                "0x4718fa"
            ]
        },
        "ctrl_speedup::Don't speed up on shoot key": {
            "addr": "0x448e72",
            "expected": "01",
            "code": "00"
        }
    },
    "codecaves": {}
}
