{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ctrl_speedup::Make ctrl speedup work outside of replays": {
            "code": "66 90",
            "addr": "0x448e56",
            "expected": "7525"
        },
        "ctrl_speedup::Don't speed up on C key": {
            "code": "66 90",
            "addr": [
                "0x401e3f",
                "0x402014"
            ]
        },
        "ctrl_speedup::Don't speed up on shoot key": {
            "addr": "0x448e5e",
            "expected": "01020000",
            "code": "00020000"
        }
    },
    "codecaves": {}
}
