{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ctrl_speedup::Make ctrl speedup work outside of replays": {
            "code": "66 90",
            "addr": "0x44e627",
            "expected": "7568"
        },
        "ctrl_speedup::Don't speed up on shoot key": {
            "addr": "0x44e62f",
            "expected": "01020000",
            "code": "00020000"
        }
    },
    "codecaves": {}
}
