{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.anm-buffers.alloc": {
            "addr": "0x48954f",
            "expected": "6808060000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.alloc)]"
        },
        "ExpHP.anm-buffers.dealloc": {
            "addr": "0x44c97c",
            "expected": "e86f3a0400",
            "code": "E8 [codecave:of(ExpHP.anm-buffers.dealloc)]"
        },
        "ExpHP.anm-buffers.search": {
            "addr": "0x488510",
            "code": "e9[codecave:ExpHP.anm-buffers.new-search]"
        },
        "ExpHP.anm-buffers.no-fast-alloc": {
            "addr": "0x489479",
            "code": "e800000000c704244f954800c3"
        },
        "ExpHP.anm-buffers.set-id(edi, ecx)": {
            "expected": "898f44050000",
            "addr": [
                "0x487c72",
                "0x487d2c",
                "0x487de2",
                "0x487e9c"
            ],
            "code": "E8 [codecave:of(ExpHP.anm-buffers.set-id(edi, ecx))] // 90"
        }
    },
    "codecaves": {
        "ExpHP.anm-buffers.game-data": "08060000440500009f03490000000000",
        "of(ExpHP.anm-buffers.alloc)": "e8[codecave:ExpHP.anm-buffers.new-alloc-vm]e800000000c704245c954800c3",
        "of(ExpHP.anm-buffers.dealloc)": "56e8[codecave:ExpHP.anm-buffers.new-dealloc-vm]c3",
        "of(ExpHP.anm-buffers.set-id(edi, ecx))": "50515257e8[codecave:ExpHP.anm-buffers.assign-our-id]5a5989c158c3"
    }
}
