{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.anm-buffers.alloc": {
            "addr": "0x46f6ef",
            "expected": "68fc050000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.alloc)]"
        },
        "ExpHP.anm-buffers.dealloc": {
            "addr": "0x43b941",
            "expected": "e899900300",
            "code": "E8 [codecave:of(ExpHP.anm-buffers.dealloc)]"
        },
        "ExpHP.anm-buffers.search": {
            "addr": "0x46efa0",
            "code": "e9[codecave:ExpHP.anm-buffers.new-search]"
        },
        "ExpHP.anm-buffers.no-fast-alloc": {
            "addr": "0x46f619",
            "code": "e800000000c70424eff64600c3"
        },
        "ExpHP.anm-buffers.set-id(edi, ecx)": {
            "expected": "898f38050000",
            "addr": [
                "0x46e872",
                "0x46e92c",
                "0x46e9e2",
                "0x46ea9c"
            ],
            "code": "E8 [codecave:of(ExpHP.anm-buffers.set-id(edi, ecx))] // 90"
        }
    },
    "codecaves": {
        "ExpHP.anm-buffers.game-data": "fc05000038050000ac494700efbeadde00000000",
        "of(ExpHP.anm-buffers.alloc)": "e8[codecave:ExpHP.anm-buffers.new-alloc-vm]e800000000c70424fcf64600c3",
        "of(ExpHP.anm-buffers.dealloc)": "56e8[codecave:ExpHP.anm-buffers.new-dealloc-vm]c3",
        "of(ExpHP.anm-buffers.set-id(edi, ecx))": "50515257e8[codecave:ExpHP.anm-buffers.assign-our-id]5a5989c158c3"
    }
}
