{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.anm-buffers.alloc": {
            "addr": "0x475a1f",
            "expected": "68fc050000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.alloc)]"
        },
        "ExpHP.anm-buffers.dealloc": {
            "addr": "0x438bfe",
            "expected": "e85c570400",
            "code": "E8 [codecave:of(ExpHP.anm-buffers.dealloc)]"
        },
        "ExpHP.anm-buffers.search": {
            "addr": "0x47530d",
            "expected": "8b96dc000000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.search)] // CC"
        },
        "ExpHP.anm-buffers.no-fast-alloc": {
            "addr": "0x475949",
            "code": "e800000000c704241f5a4700c3"
        }
    },
    "codecaves": {
        "ExpHP.anm-buffers.game-data": "fc050000380500008da74700",
        "of(ExpHP.anm-buffers.alloc)": "e8[codecave:ExpHP.anm-buffers.new-alloc-vm]e800000000c704242c5a4700c3",
        "of(ExpHP.anm-buffers.dealloc)": "56e8[codecave:ExpHP.anm-buffers.new-dealloc-vm]c3",
        "of(ExpHP.anm-buffers.search)": "50e8[codecave:ExpHP.anm-buffers.new-search]e800000000c704245a534700c3"
    }
}
