{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.anm-buffers.alloc": {
            "addr": "0x46f6ef",
            "expected": "68fc050000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.alloc)]"
        },
        "ExpHP.anm-buffers.dealloc": {
            "addr": "0x43b941",
            "expected": "e899900300",
            "code": "E8 [codecave:of(ExpHP.anm-buffers.dealloc)]"
        },
        "ExpHP.anm-buffers.search": {
            "addr": "0x46efc4",
            "expected": "8b96dc000000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.search)] // CC"
        },
        "ExpHP.anm-buffers.no-fast-alloc": {
            "addr": "0x46f619",
            "code": "e800000000c70424eff64600c3"
        }
    },
    "codecaves": {
        "ExpHP.anm-buffers.game-data": "fc05000038050000ac494700",
        "of(ExpHP.anm-buffers.alloc)": "e8[codecave:ExpHP.anm-buffers.new-alloc-vm]e800000000c70424fcf64600c3",
        "of(ExpHP.anm-buffers.dealloc)": "56e8[codecave:ExpHP.anm-buffers.new-dealloc-vm]c3",
        "of(ExpHP.anm-buffers.search)": "50e8[codecave:ExpHP.anm-buffers.new-search]e800000000c7042403f04600c3"
    }
}
