{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "protection": "0x40",
        "ExpHP.anm-buffers.game-data": "00060000 // 38050000 // 50B24700",
        "of(ExpHP.anm-buffers.alloc)": "E8[codecave:ExpHP.anm-buffers.new-alloc-vm] // E800000000C70424596B4700C3",
        "of(ExpHP.anm-buffers.dealloc)": "56 // E8[codecave:ExpHP.anm-buffers.new-dealloc-vm] // C3",
        "of(ExpHP.anm-buffers.search)": "50 // E8[codecave:ExpHP.anm-buffers.new-search] // E800000000C70424DA644700C3"
    },
    "binhacks": {
        "ExpHP.anm-buffers.alloc": {
            "addr": "0x476b54",
            "expected": "e8f7460000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.alloc)]"
        },
        "ExpHP.anm-buffers.dealloc": {
            "addr": "0x476083",
            "expected": "e8f8510000",
            "code": "E8 [codecave:of(ExpHP.anm-buffers.dealloc)]"
        },
        "ExpHP.anm-buffers.search": {
            "addr": "0x47648d",
            "expected": "8b8edc060000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.search)] // CC"
        }
    }
}
