{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "ExpHP.anm-buffers.alloc": {
            "addr": "0x476b54",
            "expected": "e8f7460000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.alloc)]"
        },
        "ExpHP.anm-buffers.dealloc": {
            "addr": "0x476083",
            "expected": "e8f8510000",
            "code": "E8 [codecave:of(ExpHP.anm-buffers.dealloc)]"
        },
        "ExpHP.anm-buffers.search": {
            "addr": "0x47648d",
            "expected": "8b8edc060000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.search)] // CC"
        }
    },
    "codecaves": {
        "ExpHP.anm-buffers.game-data": "000600003805000050b24700",
        "ExpHP.anm-buffers.layer-data": "c0f84600dc060000e406000018000000340500006000000024000000070000001800000026000000",
        "of(ExpHP.anm-buffers.alloc)": "e8[codecave:ExpHP.anm-buffers.new-alloc-vm]e800000000c70424596b4700c3",
        "of(ExpHP.anm-buffers.dealloc)": "56e8[codecave:ExpHP.anm-buffers.new-dealloc-vm]c3",
        "of(ExpHP.anm-buffers.search)": "50e8[codecave:ExpHP.anm-buffers.new-search]e800000000c70424da644700c3"
    }
}
