{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "codecaves": {
        "protection": "0x40",
        "ExpHP.anm-buffers.game-data": "18060000 // 50050000 // 51484800",
        "of(ExpHP.anm-buffers.alloc)": "E8[codecave:ExpHP.anm-buffers.new-alloc-vm] // E800000000C70424D9FB4700C3",
        "of(ExpHP.anm-buffers.dealloc)": "56 // E8[codecave:ExpHP.anm-buffers.new-dealloc-vm] // C3",
        "of(ExpHP.anm-buffers.search)": "50 // E8[codecave:ExpHP.anm-buffers.new-search] // E800000000C70424EAF44700C3"
    },
    "binhacks": {
        "ExpHP.anm-buffers.alloc": {
            "addr": "0x47fbd4",
            "expected": "e8784c0000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.alloc)]"
        },
        "ExpHP.anm-buffers.dealloc": {
            "addr": "0x47f0c3",
            "expected": "e8b9570000",
            "code": "E8 [codecave:of(ExpHP.anm-buffers.dealloc)]"
        },
        "ExpHP.anm-buffers.search": {
            "addr": "0x47f49d",
            "expected": "8b8ef0060000",
            "code": "E9 [codecave:of(ExpHP.anm-buffers.search)] // CC"
        }
    }
}
