{
    "COMMENT": "This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.",
    "binhacks": {
        "continue patch::Remove game over music": {
            "addr": "0x4337f4",
            "expected": "6834104a00",
            "code": "E9 [codecave:of(continue patch::Remove game over music)]"
        },
        "continue patch::Fix the continue option": {
            "addr": "0x4347e5",
            "expected": "33c0 // 3985f4010000",
            "code": "E9 [codecave:of(continue patch::Fix the continue option)] // CCCCCC"
        }
    },
    "codecaves": {
        "ExpHP.continue.pause-bgm": "55 89E5 56 57 // 6A00 // 6A06 // BF44104A00 // B8E8F44C00 // B960494500 // FFD1 // 5F 5E 89EC 5D // C3",
        "ExpHP.continue.do-continue": "55 89E5 56 57 // C705 980C4B00 02000000 // C705 A00C4B00 02000000 // C705 9C0C4B00 00000000 // C705 A40C4B00 00000000 // FF35 9C0C4B00 // FF35 980C4B00 // FF35 E4434B00 // B8 60CE4100 // FFD0 // FF35 A40C4B00 // FF35 A00C4B00 // FF35 E4434B00 // B8 40CF4100 // FFD0 // C705 440C4B00 00000000 // C705 480C4B00 00000000 // 8B1DD00C4B00 // B8 400C4B00 // B9 702D4200 // FFD1 // FF35 14454B00 // B8 B0854300 // FFD0 // 8B0D C40C4B00 // 41 // BA 09000000 // 39D1 // 0F4FCA // 89 0DC40C4B00 // 8B7508 // C7460400000000 // 8B7508 // B8 60294300 // FFD0 // 5F 5E 89EC 5D // C20400",
        "of(continue patch::Remove game over music)": "E8 [codecave:ExpHP.continue.pause-bgm] // E800000000 // C704242C384300 // C3",
        "of(continue patch::Fix the continue option)": "833DB00C4B0007 // 7402 // EB15 // 31C0 // 3985F4010000 // E800000000 // C70424ED474300 // C3 // 55 // E8 [codecave:ExpHP.continue.do-continue] // 5F // 5E // 5B // 5D // E800000000 // C7042400484300 // C3"
    }
}
